Repository visual-framework/vf-core, pull requests merged in 2018-11, with the labels that each got.

#18 wip: data protection (GDPR) component
  assets/scss/styles.scss
  assets/scss/variables/vf-global-variables.scss
  components/blocks/vf-data-protection-banner/CHANGELOG.md
  components/blocks/vf-data-protection-banner/README.md
  components/blocks/vf-data-protection-banner/index.scss
  components/blocks/vf-data-protection-banner/package.json
  components/blocks/vf-data-protection-banner/vf-data-protection-banner.config.yml
  components/blocks/vf-data-protection-banner/vf-data-protection-banner.hbs
  components/blocks/vf-data-protection-banner/vf-data-protection-banner.js
  components/blocks/vf-data-protection-banner/vf-data-protection-banner.scss
  components/grids/vf-grid/vf-grid.scss
Labels: Status: On Hold

#38 updates to remove the iframe preview padding
  assets/scss/_shame.scss
Labels: Type: Bug

#49 Fix uncaught type error in vf-tabs
  components/blocks/vf-tabs/vf-tabs.js
Labels: Type: Bug

#64 updates pattern generator
  tools/component-generator/index.js
  tools/component-generator/templates/_component.config.yml
  tools/component-generator/templates/_index.scss
  tools/component-generator/templates/_package.json
Labels: Status: Review Needed, Type: Chore

#66 WIP: initial banner pattern
  assets/scss/styles.scss
  components/vf-banner/CHANGELOG.md
  components/vf-banner/README.md
  components/vf-banner/index.scss
  components/vf-banner/package.json
  components/vf-banner/vf-banner--gdpr.hbs
  components/vf-banner/vf-banner--phase-inline.hbs
  components/vf-banner/vf-banner--phase.hbs
  components/vf-banner/vf-banner.config.yml
  components/vf-banner/vf-banner.hbs
  components/vf-banner/vf-banner.js
  components/vf-banner/vf-banner.scss
Labels: WIP

#68 removes bad yaml
  components/vf-banner/vf-banner.config.yml
Labels: Priority: Critical, Status: Feedback Needed, Type: Bug
