Repository visual-framework/vf-core, pull requests merged in 2019-12, with the labels that each got.

#668 component: vf-u-width
  components/vf-utility-classes/vf-u-width.scss
  components/vf-utility-classes/vf-utility-classes--width.njk
  components/vf-utility-classes/vf-utility-classes.scss
Labels: Type: Component or Pattern, Type: Feature

#669 the one where we update vf-hero to work with full width and inlay
  components/vf-componenet-rollup/index.scss
  components/vf-hero/vf-hero--example.njk
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.scss
  components/vf-lens/.npmignore
  components/vf-lens/CHANGELOG.md
  components/vf-lens/README.md
  components/vf-lens/index.scss
  components/vf-lens/package.json
  components/vf-lens/vf-lens.config.yml
  components/vf-lens/vf-lens.js
  components/vf-lens/vf-lens.njk
  components/vf-lens/vf-lens.scss
  components/vf-lens/vf-lens.variables.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Refactor

#667 ENHANCEMENT: Improve vf-core logging
  tools/gulp-tasks/vf-css.js
Labels: Type: Enhancement

#670 bug: ebi-header-footer
  components/ebi-header-footer/ebi-header-footer--header.scss
  components/ebi-header-footer/ebi-header-footer.scss
Labels: Priority: Medium, Type: Bug

#671 the one where we update the navigation and start adding global things
  components/vf-navigation/vf-navigation--main.scss
  components/vf-navigation/vf-navigation.config.yml
  components/vf-navigation/vf-navigation.njk
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Refactor

#672 the one with the quick update to the masthead component
  components/vf-masthead/vf-masthead--inlay.njk
  components/vf-masthead/vf-masthead.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Refactor

#674 the one where we make some incremental layout fixes
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-header/vf-header.scss
  components/vf-hero/vf-hero.scss
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/vf-navigation--main.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#684 CHORE - Push some components to v1.0 stable
  PUBLISHING.md
  components/ebi-vf1-integration/CHANGELOG.md
  components/embl-conditional-edit/CHANGELOG.md
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-meta-properties/CHANGELOG.md
  components/embl-favicon/CHANGELOG.md
  components/embl-grid/CHANGELOG.md
  components/embl-logo/CHANGELOG.md
  components/vf-badge/CHANGELOG.md
  components/vf-banner/CHANGELOG.md
  components/vf-blockquote/CHANGELOG.md
  components/vf-box/CHANGELOG.md
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-button/CHANGELOG.md
  components/vf-card/CHANGELOG.md
  components/vf-code-example/CHANGELOG.md
  components/vf-componenet-rollup/CHANGELOG.md
  components/vf-content/CHANGELOG.md
  components/vf-deprecated/CHANGELOG.md
  components/vf-design-tokens/CHANGELOG.md
  components/vf-divider/CHANGELOG.md
  components/vf-favicon/CHANGELOG.md
  components/vf-font-plex-mono/CHANGELOG.md
  components/vf-font-plex-sans/CHANGELOG.md
  components/vf-footer/CHANGELOG.md
  components/vf-grid-page/CHANGELOG.md
  components/vf-grid-page/README.md
  components/vf-grid/CHANGELOG.md
  components/vf-heading/CHANGELOG.md
  components/vf-intro/CHANGELOG.md
  components/vf-intro/README.md
  components/vf-lede/CHANGELOG.md
  components/vf-lede/README.md
  components/vf-link-list/CHANGELOG.md
  components/vf-link/CHANGELOG.md
  components/vf-list/CHANGELOG.md
  components/vf-list/README.md
  components/vf-logo/CHANGELOG.md
  components/vf-logo/README.md
  components/vf-navigation/CHANGELOG.md
  components/vf-no-js/CHANGELOG.md
  components/vf-page-header/CHANGELOG.md
  components/vf-page-header/README.md
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-utilities/CHANGELOG.md
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/README.md
  components/vf-summary-container/CHANGELOG.md
  components/vf-summary-container/README.md
  components/vf-summary/CHANGELOG.md
  components/vf-summary/README.md
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/README.md
  components/vf-text/CHANGELOG.md
  components/vf-utility-classes/CHANGELOG.md
  components/vf-utility-classes/README.md
Labels: Type: Chore, Type: Component or Pattern

#686 the one where we try and remove another excess <div> element for content-hub-html
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/embl-content-hub-loader.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#687 the one that makes the banner 'fit' better when in a page
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner--fixed.scss
  components/vf-banner/vf-banner--phase.scss
  components/vf-banner/vf-banner.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#689 chore: update dependencies
  package.json
  yarn.lock
Labels: Priority: Low, Type: Chore

#694 chore: embl-grid--sidebar gap
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.scss
Labels: Type: Chore

#688 enhancement: improve-publishing-workflow
  PUBLISHING.md
  package.json
Labels: Priority: Medium, Type: Enhancement

#696 chore: update release script for master branch
  PUBLISHING.md
Labels: Type: Chore
