Repository visual-framework/vf-core, pull requests merged in 2019-03, with the labels that each got.

#276 Feature/update embl ontology client
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.hbs
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
Labels: Type: Pattern, Type: Refactor

#282 adds vf-icon--avatar.svg and updates vf-summary--profile
  components/vf-summary/assets/vf-icon--avatar.svg
  components/vf-summary/vf-summary--profile.hbs
  components/vf-summary/vf-summary--profile.scss
  components/vf-summary/vf-summary.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Changelog, Type: Refactor

#283 enhancement: Block border bottom colours on links
  components/vf-sass-config/mixins/_links.scss
  components/vf-sass-config/variables/vf-global-variables.scss
Labels: Changelog, Type: Enhancement

#287 chore: Integrate shame colour as "gray-light"
  components/embl-grid/embl-grid.scss
  components/vf-sass-config/mixins/_divider.scss
  components/vf-sass-config/mixins/_utility--spacing.scss
  components/vf-sass-config/mixins/_vf-mixins.scss
  components/vf-sass-config/mixins/_vf-utility-mixins.scss
  components/vf-sass-config/variables/_vf-variables.scss
  components/vf-sass-config/variables/_vf-variables.shame.scss
  components/vf-sass-config/variables/vf-ui-colors.map.scss
Labels: Changelog, Type: Chore

#286 normalise: underline links
  components/vf-sass-config/mixins/_links.scss
Labels: Changelog, Type: Normalisation

#281 pattern/support-vf-link-in-vf-masthead
  components/embl-group-page/embl-group-page.hbs
  components/vf-masthead/vf-masthead--inlay.hbs
  components/vf-masthead/vf-masthead--with-title-block.hbs
  components/vf-masthead/vf-masthead.hbs
  components/vf-masthead/vf-masthead.scss
  npm-shrinkwrap.json
  tools/frctl-mandelbrot-embl-subtheme/views/partials/header.nunj
Labels: Type: Chore

#290 bug: stop emblContentHub from running twice
  components/embl-content-hub-loader/embl-content-hub-loader.js
Labels: Changelog, Type: Bug

#291 bug: badges don't need normalisations
  components/vf-badge/vf-badge.scss
Labels: Type: Bug

#294 adds image in links list
  components/vf-link-list/vf-link-list--has-images.hbs
  components/vf-link-list/vf-link-list.scss
Labels: Changelog, Type: Pattern

#295 Updates/vf links list grid
  components/vf-link-list/vf-link-list--has-images.hbs
  components/vf-link-list/vf-link-list.scss
Labels: Type: Enhancement, Type: Pattern

#296 bug: Swab svgo fro svgmin
  gulpfile.js
  npm-shrinkwrap.json
  package.json
Labels: Type: Bug, Type: Chore

#307 pattern: Update hbs template for vf-intro
  components/vf-intro/vf-intro.config.yml
  components/vf-intro/vf-intro.hbs
  components/vf-lede/vf-lede.config.yml
  components/vf-lede/vf-lede.hbs
  npm-shrinkwrap.json
Labels: Type: Chore, Type: Pattern

#306 Pattern/vf-summary--has-image
  components/vf-core/index.scss
  components/vf-summary/index.scss
  components/vf-summary/package.json
  components/vf-summary/vf-summary--has-image.hbs
  components/vf-summary/vf-summary--has-image.scss
Labels: Changelog, Type: Pattern

#288 Feature/embl breadcrumbs enhancements
  components/embl-breadcrumbs-lookup/assets/embl-breadcrumbs-lookup-ghost.svg
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.hbs
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.scss
  components/embl-group-page/embl-group-page.hbs
Labels: Changelog, Type: Enhancement

#311 Use `/develop` assets from the CDN
  components/_previews/_preview--containers.hbs
  components/_previews/_preview--grids.hbs
  components/_previews/_preview--nogrid.hbs
  components/_previews/_preview.hbs
  components/embl-boilerplate-page/embl-boilerplate-page.hbs
  components/embl-group-page/embl-group-page--contact.hbs
  components/embl-group-page/embl-group-page.hbs
  components/embl-subsite-page/embl-subsite-page.hbs
  components/vf-boilerplate-page/vf-boilerplate-page.hbs
  tools/frctl-mandelbrot-embl-subtheme/views/partials/scripts.nunj
  tools/frctl-mandelbrot-embl-subtheme/views/partials/stylesheets.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/scripts.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/stylesheets.nunj
Labels: Type: Chore

#318 Feature/nunjucks extensions
  components/embl-boilerplate-page/embl-boilerplate-page.njk
  components/embl-group-page/embl-group-page.njk
  components/embl-subsite-page/embl-subsite-page.njk
  components/vf-boilerplate-page/vf-boilerplate-page.njk
  components/vf-heading/README.md
  components/vf-heading/vf-heading.njk
  fractal.js
  tools/vf-frctl-extensions/REAMDE.md
  tools/vf-frctl-extensions/codeblock.js
Labels: Changelog, Type: Feature

#298 Doc cleanup
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/changelog/index.njk
  docs/contributing/components.njk
  docs/contributing/file-structure.njk
  docs/contributing/getting-started.md
  docs/contributing/index.njk
  docs/contributing/setting-up.njk
  docs/contributing/user-base.njk
  docs/guidelines/global-token-variables.njk
  docs/guidelines/html.njk
  docs/guidelines/index.njk
  tools/vf-frctl-theme/views/pages/doc.njk
Labels: Changelog, Type: Documentation

#313 Refactor/vf masthead
  components/vf-masthead/vf-masthead--inlay.njk
  components/vf-masthead/vf-masthead.njk
  components/vf-masthead/vf-masthead.scss
  components/vf-sass-config/variables/_vf-variables.scss
  components/vf-sass-config/variables/vf-border-radius.scss
  components/vf-sass-config/variables/vf-border-radius.variables.scss
  components/vf-sass-config/variables/vf-breakpoints.scss
  components/vf-sass-config/variables/vf-breakpoints.variables.scss
  components/vf-sass-config/variables/vf-colors.custom-properties.scss
  components/vf-sass-config/variables/vf-colors.map.scss
  components/vf-sass-config/variables/vf-font--monospace.scss
  components/vf-sass-config/variables/vf-font--sans.scss
  components/vf-sass-config/variables/vf-font-families.variables.scss
  components/vf-sass-config/variables/vf-global-variables.scss
  components/vf-sass-config/variables/vf-links.variables.scss
  components/vf-sass-config/variables/vf-spacing.custom-properties.scss
  components/vf-sass-config/variables/vf-spacing.map.scss
  components/vf-sass-config/variables/vf-ui-colors.custom-properties.scss
  components/vf-sass-config/variables/vf-ui-colors.map.scss
  gulpfile.js
  npm-shrinkwrap.json
Labels: Changelog, Type: Pattern, Type: Refactor

#328 Fix/sass includes
  components/vf-link/package.json
  components/vf-link/vf-link--secondary.scss
  components/vf-link/vf-link.scss
  components/vf-link/vf-link.variables.scss
  components/vf-search/CHANGELOG.md
  components/vf-search/README.md
  components/vf-search/index.scss
  components/vf-search/package.json
  components/vf-search/vf-search.js
  components/vf-search/vf-search.scss
  components/vf-search/vf-search.variables.scss
  components/vf-summary/index.scss
  components/vf-summary/vf-summary.variables.scss
  components/vf-text/index.scss
Labels: Type: Bug

#330 Fix naming of fonts on npm
  components/vf-font-plex-mono/CHANGELOG.md
  components/vf-font-plex-mono/package.json
  components/vf-font-plex-sans/CHANGELOG.md
  components/vf-font-plex-sans/package.json
Labels: Type: Bug
