Repository visual-framework/vf-core, pull requests merged in 2019-10, with the labels that each got.

#584 Bug: fix vf1 compatibility on input boxes
  components/ebi-vf1-integration/ebi-vf1-integration.njk
  components/ebi-vf1-integration/ebi-vf1-integration.scss
Labels: Type: Bug

#585 FEATURE - precompiled nunjucks templates
  .gitignore
  fractal.js
  package.json
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-build.js
  tools/gulp-tasks/vf-fractal.js
  tools/gulp-tasks/vf-templates-precompile.js
  tools/gulp-tasks/vf-watch.js
Labels: Type: Feature

#587 BUG: Correct font demos and monospace mixin
  components/vf-componenet-rollup/index.scss
  components/vf-font-plex-mono/README.md
  components/vf-font-plex-mono/vf-font-plex-mono.config.yml
  components/vf-font-plex-mono/vf-font-plex-mono.njk
  components/vf-font-plex-mono/vf-font-plex-mono.scss
  components/vf-font-plex-sans/README.md
  components/vf-font-plex-sans/vf-font-plex-sans.config.yml
  components/vf-font-plex-sans/vf-font-plex-sans.njk
  components/vf-font-plex-sans/vf-font-plex-sans.scss
  components/vf-sass-config/mixins/_typography.scss
Labels: Type: Bug, Type: Component or Pattern

#586 Fixes/hardcoded links
  components/embl-logo/embl-logo.config.yml
  components/embl-logo/embl-logo.njk
  components/vf-article-meta-information/vf-article-meta-information.config.yml
  components/vf-article-meta-information/vf-article-meta-information.njk
  components/vf-badge/vf-badge.config.yml
  components/vf-badge/vf-badge.njk
  components/vf-banner/vf-banner--inline.njk
  components/vf-banner/vf-banner--top.njk
  components/vf-banner/vf-banner.config.yml
  components/vf-breadcrumbs/vf-breadcrumbs--with-related.njk
  components/vf-breadcrumbs/vf-breadcrumbs.config.yml
  components/vf-breadcrumbs/vf-breadcrumbs.njk
  components/vf-button/vf-button.config.yml
  components/vf-button/vf-button.njk
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-discussion/vf-discussion.config.yml
  components/vf-discussion/vf-discussion.njk
  components/vf-footer/vf-footer.config.yml
  components/vf-footer/vf-footer.njk
  components/vf-intro/vf-intro.config.yml
  components/vf-intro/vf-intro.njk
  components/vf-link-list/vf-link-list.config.yml
  components/vf-link-list/vf-link-list.njk
  components/vf-link/vf-link.config.yml
  components/vf-link/vf-link.njk
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.njk
  components/vf-masthead/vf-masthead--inlay.njk
  components/vf-masthead/vf-masthead--with-title-block.njk
  components/vf-masthead/vf-masthead.config.yml
  components/vf-masthead/vf-masthead.njk
  components/vf-navigation/vf-navigation.config.yml
  components/vf-navigation/vf-navigation.njk
  components/vf-pagination/package.json
  components/vf-pagination/vf-pagination--compact.njk
  components/vf-pagination/vf-pagination--expanded.njk
  components/vf-pagination/vf-pagination--first-last.njk
  components/vf-pagination/vf-pagination--full.njk
  components/vf-pagination/vf-pagination.config.yml
  components/vf-pagination/vf-pagination.njk
  components/vf-summary/vf-summary--article.njk
  components/vf-summary/vf-summary--has-image.njk
  components/vf-summary/vf-summary--job.njk
  components/vf-summary/vf-summary--news-has-image.njk
  components/vf-summary/vf-summary--news.njk
  components/vf-summary/vf-summary--profile.njk
  components/vf-summary/vf-summary--publication.njk
  components/vf-summary/vf-summary.config.yml
  components/vf-summary/vf-summary.njk
  components/vf-video-teaser/vf-video-teaser.config.yml
  components/vf-video-teaser/vf-video-teaser.njk
  components/vf-video/vf-video.config.yml
  components/vf-video/vf-video.njk
Labels: Status: Review Needed, Type: Chore, Type: Refactor

#590 Documentation: publishing guide
  PUBLISHING.md
Labels: Type: Documentation

#593 bug: fix-font-css-import
  components/vf-font-plex-mono/vf-font-plex-mono.scss
  components/vf-font-plex-sans/vf-font-plex-sans.scss
Labels: Priority: High, Type: Bug

#595 Enhancement: typography mixin
  components/vf-font-plex-mono/vf-font-plex-mono.scss
  components/vf-font-plex-sans/vf-font-plex-sans.scss
  components/vf-sass-config/mixins/_typography.scss
  components/vf-sass-config/variables/vf-global-variables.scss
Labels: Type: Enhancement

#591 Release: vf-core-v2.0.0-beta.4
  package.json
Labels: Type: Chore

#596 The One Where We Add Tree Navigation V0.0.1
  components/vf-componenet-rollup/index.scss
  components/vf-figure/assets/training-cover.png
  components/vf-tree/.npmignore
  components/vf-tree/CHANGELOG.md
  components/vf-tree/README.md
  components/vf-tree/index.scss
  components/vf-tree/package.json
  components/vf-tree/vf-tree.config.yml
  components/vf-tree/vf-tree.js
  components/vf-tree/vf-tree.njk
  components/vf-tree/vf-tree.scss
  components/vf-tree/vf-tree.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern

#598 Bug: watch should ignore precompiled templates
  tools/gulp-tasks/vf-watch.js
Labels: Priority: Medium, Type: Bug

#600 Bug: Unset EBI link style on hover for links
  components/ebi-vf1-integration/ebi-vf1-integration.scss
Labels: Type: Bug

#601 Documentation: Point to slack for Chat
  README.md
  docs/getting-started/index.njk
  tools/vf-frctl-theme/views/partials/header.njk
Labels: Type: Documentation

#569 updates to the Fractal / VF Theme
  tools/vf-frctl-theme/dist/css/default.css
  tools/vf-frctl-theme/views/layouts/doc.njk
  tools/vf-frctl-theme/views/layouts/frame.njk
  tools/vf-frctl-theme/views/layouts/skeleton.njk
  tools/vf-frctl-theme/views/partials/browser/component-list.njk
  tools/vf-frctl-theme/views/partials/browser/panel-html.njk
  tools/vf-frctl-theme/views/partials/content/overview.njk
  tools/vf-frctl-theme/views/partials/pen/browser.njk
  tools/vf-frctl-theme/views/partials/pen/header.njk
  tools/vf-frctl-theme/views/partials/pen/preview.njk
Labels: Priority: Medium, Type: Refactor

#606 Enhancement - vf-tabs JS interactivity
  components/vf-componenet-rollup/scripts.js
  components/vf-tree/vf-tree.config.yml
  components/vf-tree/vf-tree.js
  components/vf-tree/vf-tree.njk
  components/vf-tree/vf-tree.scss
Labels: Type: Component or Pattern, Type: Enhancement

#609 bug: vf-tree-scss-missing-import
  components/vf-tree/vf-tree.scss
Labels: Priority: Medium, Type: Bug

#611 DOCUMENTATION(ish) - design token updates
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/vf-design-tokens.config.js
Labels: Type: Documentation

#610 the one where we update the colours a little bit
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-colors.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-colors.map.scss
  components/vf-design-tokens/dist/sass/vf-links.variables.scss
  components/vf-design-tokens/src/core.palette.alias.yml
  components/vf-design-tokens/src/maps/vf-colors.yml
  components/vf-design-tokens/vf-design-tokens--colours.njk
  components/vf-design-tokens/vf-design-tokens.config.js
  components/vf-design-tokens/vf-design-tokens.njk
Labels: Priority: Medium, Status: Review Needed, Type: Chore, Type: Normalisation

#614 Bug: Fix Fractal config path
  tools/gulp-tasks/vf-fractal.js
Labels: Type: Bug

#616 Feature: add fractalBuildMode
  gulpfile.js
  package.json
  tools/gulp-tasks/vf-build.js
Labels: Type: Changelog, Type: Feature

#618 Bug: fix nunjucks compilation loop
  tools/gulp-tasks/vf-watch.js
Labels: Priority: Medium, Type: Bug

#617 Feature: move config to npm
  gulpfile.js
  lerna.json
  tools/gulp-tasks/vf-build.js
  tools/vf-config/index.js
  tools/vf-config/package.json
Labels: Type: Changelog, Type: Feature

#620 releases: vf-core beta.5
  package.json
Labels: Type: Chore

#623 bug: vf--buton--outline
  components/vf-button/vf-button.scss
Labels: Priority: Low, Type: Bug

#624 Enhancement: improve build process this
  .gitlab-ci.yml
  .travis.yml
  gulpfile.js
  package.json
  tools/gulp-tasks/vf-assets.js
  tools/gulp-tasks/vf-build.js
Labels: Type: Changelog, Type: Enhancement

#632 makes the button transition slower to aid the issue in Safari
  components/vf-button/vf-button.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#631 Chore: update npm dependencies
  components/vf-design-tokens/package.json
  package.json
  tools/vf-frctl-theme/assets/js/vf-frctl-theme.js
  tools/vf-frctl-theme/assets/scss/default.scss
  tools/vf-frctl-theme/dist/js/vf-frctl-theme.js
  tools/vf-frctl-theme/dist/js/vf-frctl-theme.js.map
  tools/vf-frctl-theme/gulpfile.js
  tools/vf-frctl-theme/package.json
  tools/vf-frctl-theme/src/extensions/markdown.js
  tools/vf-frctl-theme/yarn.lock
  yarn.lock
Labels: Type: Changelog, Type: Chore

#622 Minor bugs, docs
  gulpfile.js
  tools/gulp-tasks/vf-build.js
  tools/vf-config/index.js
  tools/vf-config/package.json
Labels: Type: Documentation
