Repository visual-framework/vf-core, pull requests merged in 2019-06, with the labels that each got.

#390 Allow `vf_lede_text` to be set in `vf-intro`
  components/vf-intro/vf-intro.njk
  components/vf-lede/vf-lede.config.yml
  components/vf-lede/vf-lede.njk
Labels: Type: Bug

#397 Fix: vf-form__core references sass files from other components
  components/vf-form/vf-form__core/package-lock.json
  components/vf-form/vf-form__core/package.json
Labels: Type: Bug

#396 Feature/gulpfile optimisations
  .gitlab-ci.yml
  .travis.yml
  docs/contributing/creating-new-components.njk
  docs/contributing/setting-up.njk
  gulpfile.js
  npm-shrinkwrap.json
  package.json
Labels: Type: Feature

#400 Correct css build directory
  gulpfile.js
Labels: Priority: High, Type: Bug

#401 Feature: cleaner builds
  .gitignore
  .npmignore
  fractal.js
  gulpfile.js
  npm-shrinkwrap.json
  package.json
Labels: Type: Feature

#402 Update vf-link-list.scss
  components/vf-link-list/vf-link-list.scss
Labels: Type: Bug

#406 Add missing hyphen for grey--light
  components/vf-design-tokens/dist/json/vf-font--sans.ios.json
  components/vf-design-tokens/dist/json/vf-ui-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-ui-colors.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-ui-colors.map.scss
  components/vf-design-tokens/src/maps/vf-ui-colors.yml
Labels: Type: Bug

#405 fix: core-component-asset-paths
  gulpfile.js
Labels: Type: Chore

#418 Fixes/colors
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.scss
  components/embl-grid/embl-grid.scss
  components/embl-group-page/embl-group-page.scss
  components/vf-activity-group/vf-activity-group.scss
  components/vf-activity-list/vf-activity-list.scss
  components/vf-article-meta-information/vf-article-meta-information.scss
  components/vf-badge/vf-badge.scss
  components/vf-banner/vf-banner.variables.scss
  components/vf-box/vf-box--factoid.scss
  components/vf-box/vf-box.scss
  components/vf-button/vf-button.scss
  components/vf-code-example/vf-code-example.scss
  components/vf-design-tokens/dist/json/vf-ui-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-ui-colors.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-ui-colors.map.scss
  components/vf-design-tokens/src/maps/vf-ui-colors.yml
  components/vf-discussion/vf-discussion.scss
  components/vf-footer/vf-footer.scss
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__radio/vf-form__radio.scss
  components/vf-form/vf-form__select/vf-form__select.scss
  components/vf-form/vf-form__textarea/vf-form__textarea.scss
  components/vf-global-header/vf-global-header.scss
  components/vf-header/vf-header.scss
  components/vf-heading/vf-heading.scss
  components/vf-link-list/vf-link-list.scss
  components/vf-link/vf-link.variables.scss
  components/vf-masthead/README.md
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--global.scss
  components/vf-navigation/vf-navigation--main.scss
  components/vf-pagination/vf-pagination.scss
  components/vf-sass-config/mixins/_blockquote.scss
  components/vf-sass-config/mixins/_divider.scss
  components/vf-sass-config/mixins/_links.scss
  components/vf-tabs/vf-tabs.scss
Labels: Status: Review Needed, Type: Bug

#431 Fix: docs should soft fail when vf-design-tokens aren't present
  docs/styles/colours.config.js
  docs/styles/spacing.config.js
  docs/styles/typography.config.js
Labels: Type: Bug

#435 chore: cleanup autocomment
  .github/auto-comment.yml
Labels: Type: Chore

#439 Enhancement: vf-blockquote
  components/vf-content/vf-content.njk
  components/vf-content/vf-content.scss
  components/vf-sass-config/mixins/_blockquote.scss
Labels: Type: Enhancement

#437 bug: conditional-edit-order-of-operation
  components/embl-conditional-edit/embl-conditional-edit.js
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  components/vf-componenet-rollup/scripts.js
Labels: Type: Bug

#441 the one that fixes quite a lot of small issues with vf-core and vf-wp
  components/vf-box/vf-box.variables.scss
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-header/vf-header.scss
  components/vf-navigation/vf-navigation--main.scss
Labels: Status: Review Needed, Type: Bug
