Repository visual-framework/vf-core, pull requests merged in 2019-02, with the labels that each got.

#198 Only use half page grid gap for nav
  components/embl-subsite-page/embl-subsite-page.hbs
  components/vf-core/index.scss
  components/vf-global-header/vf-global-header.hbs
  components/vf-header/vf-header.hbs
  components/vf-header/vf-header.scss
  components/vf-inlay/vf-inlay.hbs
  components/vf-inlay/vf-inlay.scss
  components/vf-masthead/vf-masthead--inlay.hbs
  components/vf-masthead/vf-masthead--supports.scss
  components/vf-masthead/vf-masthead.hbs
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/index.scss
  components/vf-navigation/package.json
  components/vf-navigation/vf-navigation--additional.hbs
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--global.hbs
  components/vf-navigation/vf-navigation--global.scss
  components/vf-navigation/vf-navigation--main.hbs
  components/vf-navigation/vf-navigation--main.scss
  components/vf-navigation/vf-navigation--primary.hbs
  components/vf-navigation/vf-navigation--secondary.hbs
  components/vf-navigation/vf-navigation.scss
  components/vf-navigation/vf-navigation.variables.scss
  package.json
  tools/frctl-mandelbrot-embl-subtheme/views/partials/header.nunj
Labels: Type: Bug, Type: Enhancement

#225 Feature/update collated previews
  components/vf-badge/vf-badge.scss
  components/vf-box/vf-box.config.yml
  components/vf-button/vf-button--sizes.hbs
  components/vf-button/vf-button--variants.hbs
  components/vf-button/vf-button.hbs
  components/vf-link/vf-link.hbs
  components/vf-sass-config/mixins/_links.scss
  tools/frctl-mandelbrot-embl-subtheme/views/partials/browser/panel-html.nunj
  tools/frctl-mandelbrot-embl-subtheme/views/partials/pen/preview.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/browser/panel-html.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/pen/preview.nunj
Labels: Changelog, Type: Enhancement

#226 Further improve/simplify blocks/element preview
  components/_previews/_preview--blocks.hbs
  components/_previews/_preview--elements.hbs
  components/vf-badge/vf-badge--examples.hbs
  components/vf-badge/vf-badge.config.yml
  components/vf-banner/vf-banner.config.yml
  components/vf-button/vf-button--examples.hbs
  components/vf-button/vf-button--outline.hbs
  components/vf-button/vf-button--sizes.hbs
  components/vf-button/vf-button--styles.hbs
  components/vf-button/vf-button--variants.hbs
  components/vf-button/vf-button.config.yml
  components/vf-contact/vf-contact.config.yml
  components/vf-form/vf-form.config.yml
  components/vf-heading/vf-heading.config.yml
  components/vf-lede/vf-lede.config.yml
  components/vf-list/vf-list.config.yml
  components/vf-summary/vf-summary.config.yml
  components/vf-tag/vf-tag--examples.hbs
  components/vf-tag/vf-tag.config.yml
  npm-shrinkwrap.json
  tools/component-generator/templates/_component.config.yml
  tools/frctl-mandelbrot-embl-subtheme/views/partials/browser/browser.nunj
  tools/frctl-mandelbrot-embl-subtheme/views/partials/browser/panel-html.nunj
  tools/frctl-mandelbrot-embl-subtheme/views/partials/pen/preview.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/browser/browser.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/browser/panel-html.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/pen/preview.nunj
Labels: Type: Enhancement

#232 Fix/231 subpatterns
  components/vf-content/index.scss
  components/vf-content/vf-content.scss
  components/vf-core/index.scss
  components/vf-form/vf-form__core/README.md
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__select/index.scss
  components/vf-form/vf-form__select/vf-form__select.hbs
  gulpfile.js
Labels: Type: Bug

#236 Update vf-content.scss
  components/vf-content/vf-content.scss
Labels: Changelog, Type: Bug

#234 Enhancement/pre commit hook
  gulpfile.js
  package.json
Labels: Changelog, Type: Enhancement

#240 updates button design to include darker bottom 'border'
  components/vf-button/vf-button.scss
Labels: Type: Refactor

#247 Refactor/vf links list
  components/vf-link-list/vf-link-list--tight.hbs
  components/vf-link-list/vf-link-list.hbs
  components/vf-link-list/vf-link-list.scss
Labels: Breaking Change, Type: Refactor

#248 more design / sketch-related tweaks
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-breadcrumbs/vf-breadcrumbs.variables.scss
  components/vf-content/vf-content.scss
  components/vf-lede/vf-lede.scss
Labels: Type: Refactor

#249 Feature/js exports
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-conditional-edit/embl-conditional-edit.js
  components/embl-content-hub-loader/embl-content-hub-loader.js
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  components/embl-content-hub-loader/embl-content-hub-loader__html-imports.js
  components/embl-content-meta-properties/embl-content-meta-properties.js
  components/vf-banner/vf-banner.js
  components/vf-button/vf-button--variants.hbs
  components/vf-core/scripts.js
  components/vf-discussion/vf-discussion.js
  components/vf-lede/vf-lede.js
  components/vf-pagination/vf-pagination.js
  components/vf-search/vf-search.js
  components/vf-tabs/vf-tabs.js
  gulpfile.js
  npm-shrinkwrap.json
  package.json
  tools/component-generator/templates/_component.js
Labels: Changelog, Type: Feature

#255 Prevent screen from going extra wide on code sample
  tools/frctl-mandelbrot-embl-subtheme/views/partials/pen/preview.nunj
  tools/frctl-mandelbrot-vf-subtheme/views/partials/pen/preview.nunj
Labels: Type: Bug

#267 Favison, oof
  components/vf-favicon/CHANGELOG.md
  components/vf-favicon/package-lock.json
  components/vf-favicon/package.json
Labels: Type: Bug

#270 vf-banner-js-dependency in package.json
  components/vf-banner/package.json
Labels: Type: Bug

#269 Update vf-core to use new vf-form__core
  components/vf-content/package.json
Labels: Type: Bug

#271 Add more missing files in pattern package.json files
  components/vf-breadcrumbs/package.json
  components/vf-content/index.scss
  components/vf-masthead/index.scss
  components/vf-no-js/index.scss
  components/vf-summary/package.json
Labels: Type: Bug
