Repository visual-framework/vf-core, pull requests merged in 2019-07, with the labels that each got.

#444 enhancement: use-heading--l-alt-for-some-patterns
  components/vf-card/vf-card.scss
  components/vf-section-header/vf-section-header.scss
  components/vf-summary/vf-summary.variables.scss
  components/vf-video-teaser/vf-video-teaser.scss
Labels: Type: Chore, Type: Enhancement

#453 bug: spacing-token-naming
  components/vf-banner/vf-banner.variables.scss
  components/vf-button/vf-button.scss
  components/vf-content/vf-content.config.yml
  components/vf-content/vf-content.njk
  components/vf-content/vf-content.scss
  components/vf-inlay/vf-inlay.scss
  components/vf-link-list/vf-link-list.scss
  components/vf-page-header/vf-page-header.scss
  components/vf-sass-config/mixins/_divider.scss
  components/vf-sass-config/mixins/_lists.scss
Labels: Type: Bug

#456 Bug: fix static build path for vf-card
  components/vf-button/index.scss
  components/vf-card/vf-card.config.yml
  components/vf-content/index.scss
Labels: Type: Bug

#454 Enhancement: gulp css building, linting
  gulpfile.js
Labels: Type: Enhancement

#458 docs: Using frctl `path` with njk templates
  components/embl-group-page/embl-group-page.njk
  components/embl-logo/embl-logo.njk
  components/vf-header/vf-header--inlay.njk
  components/vf-masthead/vf-masthead--inlay.njk
  components/vf-masthead/vf-masthead--with-title-block.njk
  components/vf-summary/vf-summary--news-has-image.njk
  components/vf-video-teaser/vf-video-teaser.njk
  docs/contributing/creating-new-components.njk
  tools/component-generator/templates/_component.config.yml
Labels: Type: Chore, Type: Documentation

#461 Bug: component variant name, demo
  components/vf-heading/README.md
  components/vf-heading/vf-heading.config.yml
  components/vf-text/vf-text.config.yml
Labels: Type: Bug

#462 the one where we use variants for the vf-card component
  components/vf-card/README.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
  components/vf-card/vf-card.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Refactor

#464 Refactor: trim fractal previews
  components/_previews/_preview--containers.njk
  components/_previews/_preview--grids.njk
  components/embl-grid/embl-grid.config.yml
  components/embl-grid/embl-grid.njk
  components/vf-activity-group/vf-activity-group.config.yml
  components/vf-global-header/vf-global-header.config.yml
  components/vf-grid-page/vf-grid-page.config.yml
  components/vf-grid-page/vf-grid-page.njk
  components/vf-grid/vf-grid.config.yml
  components/vf-grid/vf-grid.njk
  components/vf-intro/vf-intro.config.yml
  components/vf-news-container/vf-news-container.config.yml
  components/vf-summary-container/vf-summary-container.config.yml
  components/vf-video-container/vf-video-container.config.yml
Labels: Type: Refactor

#465 bug: vf-conent-hub-html grid-escape
  components/embl-content-hub-loader/embl-content-hub-loader.scss
Labels: Type: Bug

#469 Chore: set percy to run only on develop
  .percy.yml
  .travis.yml
Labels: Type: Chore

#468 Docs: move design token demonstration
  components/vf-design-tokens/README.md
  components/vf-design-tokens/vf-design-tokens--colours.njk
  components/vf-design-tokens/vf-design-tokens--spacing.njk
  components/vf-design-tokens/vf-design-tokens--typography.njk
  components/vf-design-tokens/vf-design-tokens.config.js
  components/vf-design-tokens/vf-design-tokens.config.yml
  components/vf-design-tokens/vf-design-tokens.njk
  docs/styles/colours.config.js
  docs/styles/spacing.config.js
Labels: Type: Documentation

#472 adds vertical spacing for vf-lede, normalises spacing for vf-intor
  components/vf-intro/vf-intro.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#474 Guidance on how (and when) to start using vf-core #391, #339
  README.md
  docs/changelog/index.njk
  docs/contributing/creating-new-components.njk
  docs/contributing/css.njk
  docs/contributing/deprecating-components.njk
  docs/contributing/file-structure.njk
  docs/contributing/getting-started.md
  docs/contributing/global-token-variables.njk
  docs/contributing/governance.njk
  docs/contributing/index.njk
  docs/contributing/javascript.njk
  docs/contributing/naming.njk
  docs/contributing/setting-up.njk
  docs/contributing/updating-a-component.njk
  docs/contributing/user-base.njk
  docs/contributing/writing-and-language.njk
  docs/getting-started/index.njk
  docs/getting-started/right-place.njk
  docs/guidelines/versioning.njk
  docs/guidelines/visual-regression-testing.njk
  tools/vf-frctl-theme/views/layouts/doc.njk
  tools/vf-frctl-theme/views/layouts/frame.njk
  tools/vf-frctl-theme/views/pages/doc.njk
  tools/vf-frctl-theme/views/partials/browser/component-list.njk
  tools/vf-frctl-theme/views/partials/content/overview.njk
  tools/vf-frctl-theme/views/partials/header.njk
  tools/vf-frctl-theme/views/partials/pen/browser.njk
Labels: Type: Documentation

#484 BUG - Remove extra spacing from vf-badge
  components/vf-badge/vf-badge.njk
Labels: Type: Bug

#482 PERFORMANCE - Drop glob for fastglob
  gulpfile.js
  package.json
  yarn.lock
Labels: Type: Enhancement

#488 CHORE: update-footer
  components/vf-footer/vf-footer.njk
Labels: Type: Chore

#487 Enhancement: code background
  components/vf-code-example/vf-code-example.scss
Labels: Type: Enhancement

#491 CHORE - tweaks for vf-component-rollup docs, integration
  components/vf-componenet-rollup/README.md
  components/vf-componenet-rollup/vf-componenet-rollup.config.yml
  components/vf-componenet-rollup/vf-componenet-rollup.njk
Labels: Type: Chore, Type: Documentation

#493 the one where we remove a dependency to aid portability
  README.md
  components/vf-componenet-rollup/index.scss
  components/vf-grid-page/vf-grid-page.scss
  gulpfile.js
  package.json
  yarn.lock
Labels: Changelog, Status: Review Needed, Type: Refactor, Type: Strategic

#492 ENHANCEMENT - vf-grid--reset
  components/vf-utility-classes/vf-utility-classes.scss
Labels: Type: Enhancement

#495 the one where we update the card so it can be a link
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
Labels: Status: Complete, Status: Review Needed, Type: Bug, Type: Enhancement

#477 ENHANCEMENT - ship, enhance component generator
  .npmignore
  tools/component-generator/index.js
  tools/vf-frctl-theme/views/pages/doc.njk
Labels: Type: Enhancement

#497 the one where we get the form elements to work
  components/vf-form/vf-form__radio/vf-form__radio.scss
Labels: Status: Review Needed, Type: Bug

#500 the one where publications have a short summary component added
  components/vf-componenet-rollup/index.scss
  components/vf-sass-utilities/vf-et-al.scss
  components/vf-sass-utilities/vf-sass-utilities.scss
  components/vf-summary/README.md
  components/vf-summary/vf-summary--profile.scss
  components/vf-summary/vf-summary--publication.njk
  components/vf-summary/vf-summary--publication.scss
  components/vf-summary/vf-summary.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Status: In Progress, Type: Component or Pattern

#501 the one that fixes misspellings we haven't caught yet
  components/vf-badge/vf-badge.scss
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-card/vf-card.scss
  components/vf-discussion/vf-discussion.scss
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__radio/vf-form__radio.scss
  components/vf-link/vf-link--disabled.scss
  components/vf-summary/vf-summary--publication.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Priority: Medium, Type: Bug

#502 Enhancement/split gulpfile
  gulpfile.js
  tools/component-generator/index.js
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-assets.js
  tools/gulp-tasks/vf-cleanup.js
  tools/gulp-tasks/vf-component.js
  tools/gulp-tasks/vf-css.js
  tools/gulp-tasks/vf-fractal.js
  tools/gulp-tasks/vf-scripts.js
  tools/gulp-tasks/vf-watch.js
  yarn.lock
Labels: Type: Strategic

#503 the one where we add a moving label
  components/vf-componenet-rollup/scripts.js
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-form/vf-form__core/assets/float-labels.js
  components/vf-form/vf-form__core/assets/vf-form__float-labels.js
  components/vf-form/vf-form__helper/vf-form__helper.scss
  components/vf-form/vf-form__input/vf-form__input.njk
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__item/vf-form__item.njk
  components/vf-form/vf-form__label/vf-form__label.njk
  components/vf-form/vf-form__label/vf-form__label.scss
  components/vf-form/vf-form__textarea/vf-form__textarea.njk
  components/vf-form/vf-form__textarea/vf-form__textarea.scss
  components/vf-masthead/vf-masthead.njk
  components/vf-sass-utilities/_vf-screen-reader.scss
Labels: Changelog, Status: Review Needed, Type: Bug

#505 BUG - vf-footer visited link colour
  components/vf-footer/vf-footer.njk
  components/vf-footer/vf-footer.scss
  components/vf-footer/vf-footer.variables.scss
Labels: Type: Bug

#509 the one where we put autoprefixer and cssnano into the build task
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-css.js
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#516 BUG - vf-build asset copy task misses js
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-build.js
  tools/gulp-tasks/vf-fractal.js
  tools/vf-frctl-theme/views/partials/foot.njk
  tools/vf-frctl-theme/views/partials/stylesheets.njk
Labels: Priority: High, Type: Bug
