Repository visual-framework/vf-core, pull requests merged in 2019-08, with the labels that each got.

#512 the one where we tokenise the z-index
  components/vf-banner/vf-banner--fixed.scss
  components/vf-banner/vf-banner.scss
  components/vf-card/vf-card.scss
  components/vf-componenet-rollup/index.scss
  components/vf-design-tokens/dist/json/vf-zindex.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-zindex.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-zindex.map.scss
  components/vf-design-tokens/src/maps/vf-zindex.yml
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--main.scss
  components/vf-sass-config/functions/set-layer.scss
  components/vf-sass-config/functions/vf-functions.scss
  components/vf-sass-config/mixins/_utility--slide.scss
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-summary/vf-summary--profile.scss
  components/vf-summary/vf-summary.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Status: Review Needed, Type: Refactor

#518 fixes incorrect set-type mixin declaration
  components/vf-summary/vf-summary--publication.scss
Labels: Status: Review Needed, Type: Bug

#517 Bug: Handle optional js dependencies
  components/embl-conditional-edit/embl-conditional-edit.js
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  package.json
  tools/gulp-tasks/vf-scripts.js
  yarn.lock
Labels: Type: Bug

#520 Bug: check for succesful content import was in wrong spot
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
Labels: Priority: High, Type: Bug

#525 Feature: verbose output of component version
  .gitignore
  components/vf-componenet-rollup/index.scss
  gulpfile.js
  package.json
  tools/component-generator/index.js
  tools/component-generator/templates/_component.scss
  tools/gulp-tasks/vf-build.js
  tools/gulp-tasks/vf-css.js
  yarn.lock
Labels: Type: Feature

#529 Feature: allow additional collections of components
  gulpfile.js
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-css.js
  tools/gulp-tasks/vf-scripts.js
Labels: Type: Feature

#528 Bug: Windows compatibility
  gulpfile.js
  tools/gulp-tasks/vf-build.js
  tools/gulp-tasks/vf-css.js
  tools/gulp-tasks/vf-scripts.js
Labels: Type: Bug

#515 updates color and spacing for navigation, and color for content
  components/vf-content/vf-content.scss
  components/vf-header/vf-header.scss
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--main.scss
Labels: Priority: High, Type: Bug

#532 CHORE: Remove unused dependencies
  gulpfile.js
  package.json
  yarn.lock
Labels: Type: Chore

#527 Bug/minor fixes
  components/embl-content-hub-loader/embl-content-hub-loader.scss
  components/vf-componenet-rollup/scripts.js
  tools/gulp-tasks/vf-css.js
  tools/gulp-tasks/vf-scripts.js
  tools/gulp-tasks/vf-watch.js
Labels: Type: Bug, Type: Chore

#540 Bug: vf-code example formatting
  components/vf-code-example/README.md
  components/vf-code-example/vf-code-example.njk
  components/vf-code-example/vf-code-example.scss
  tools/vf-frctl-extensions/codeblock.js
  tools/vf-frctl-theme/views/pages/error.njk
  tools/vf-frctl-theme/views/partials/browser/panel-html.njk
  tools/vf-frctl-theme/views/partials/browser/panel-resources.njk
Labels: Type: Bug

#539 Bug/load vf-core version directly from `node_modules/vf-core`
  gulpfile.js
Labels: Type: Bug
