Repository visual-framework/vf-core, pull requests merged in 2019-09, with the labels that each got.

#541 chore: update readmes to say "install"
  components/embl-grid/README.md
  components/embl-logo/README.md
  components/vf-activity-group/README.md
  components/vf-activity-list/README.md
  components/vf-badge/README.md
  components/vf-blockquote/README.md
  components/vf-box/README.md
  components/vf-breadcrumbs/README.md
  components/vf-button/README.md
  components/vf-code-example/README.md
  components/vf-content/README.md
  components/vf-divider/README.md
  components/vf-favicon/README.md
  components/vf-figure/README.md
  components/vf-font-plex-mono/README.md
  components/vf-font-plex-sans/README.md
  components/vf-form/vf-form__checkbox/README.md
  components/vf-form/vf-form__core/README.md
  components/vf-form/vf-form__helper/README.md
  components/vf-form/vf-form__input/README.md
  components/vf-form/vf-form__item/README.md
  components/vf-form/vf-form__label/README.md
  components/vf-form/vf-form__radio/README.md
  components/vf-form/vf-form__select/README.md
  components/vf-form/vf-form__textarea/README.md
  components/vf-global-header/README.md
  components/vf-grid-page/README.md
  components/vf-grid/README.md
  components/vf-header/README.md
  components/vf-heading/README.md
  components/vf-intro/README.md
  components/vf-link-list/README.md
  components/vf-link/README.md
  components/vf-list/README.md
  components/vf-logo/README.md
  components/vf-masthead/README.md
  components/vf-navigation/README.md
  components/vf-news-container/README.md
  components/vf-page-header/README.md
  components/vf-section-header/README.md
  components/vf-summary-container/README.md
  components/vf-summary/README.md
  components/vf-tabs/README.md
  components/vf-text/README.md
  components/vf-video-container/README.md
  components/vf-video-teaser/README.md
  components/vf-video/README.md
Labels: Type: Chore

#544 Remove boilerplates from vf-core
  components/embl-boilerplate-page/.npmignore
  components/embl-boilerplate-page/CHANGELOG.md
  components/embl-boilerplate-page/README.md
  components/embl-boilerplate-page/embl-boilerplate-page.config.yml
  components/embl-boilerplate-page/embl-boilerplate-page.js
  components/embl-boilerplate-page/embl-boilerplate-page.njk
  components/embl-boilerplate-page/index.scss
  components/embl-boilerplate-page/package.json
  components/embl-group-page/.npmignore
  components/embl-group-page/CHANGELOG.md
  components/embl-group-page/README.md
  components/embl-group-page/embl-group-page--contact.njk
  components/embl-group-page/embl-group-page.config.yml
  components/embl-group-page/embl-group-page.js
  components/embl-group-page/embl-group-page.njk
  components/embl-group-page/embl-group-page.scss
  components/embl-group-page/embl-group-page.variables.scss
  components/embl-group-page/index.scss
  components/embl-group-page/package.json
  components/vf-componenet-rollup/index.scss
Labels: Type: Chore

#543 DOCUMENTATION - Expose documentation around vf-utility-classes and vf-sass-utilities
  components/vf-sass-utilities/README.md
  components/vf-sass-utilities/_vf-et-al.scss
  components/vf-sass-utilities/_vf-no-wrap.scss
  components/vf-sass-utilities/vf-sass-utilities.config.yml
  components/vf-sass-utilities/vf-sass-utilities.njk
  components/vf-sass-utilities/vf-sass-utilities.scss
  components/vf-utility-classes/README.md
  components/vf-utility-classes/vf-utility-classes.config.yml
  components/vf-utility-classes/vf-utility-classes.njk
Labels: Type: Component or Pattern, Type: Documentation, Type: Enhancement

#545 Chore/embl logo update
  components/embl-logo/CHANGELOG.md
  components/embl-logo/assets/logo-medium.svg
  components/embl-logo/assets/logo-small.svg
  components/embl-logo/assets/logo.png
  components/embl-logo/assets/logo.svg
  components/embl-logo/embl-logo--responsive.njk
  components/embl-logo/embl-logo.config.yml
  components/embl-logo/embl-logo.njk
  components/embl-logo/embl-logo.scss
  components/vf-global-header/vf-global-header.njk
  components/vf-logo/assets/logo-medium.svg
  components/vf-logo/assets/logo-small.svg
  components/vf-logo/assets/logo.png
  components/vf-logo/assets/logo.svg
  components/vf-logo/vf-logo--responsive.njk
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.njk
  components/vf-logo/vf-logo.scss
  tools/vf-frctl-theme/views/partials/header.njk
Labels: Type: Chore, Type: Component or Pattern

#550 Expose utility stuff as utility components
  components/vf-content/vf-content.config.yml
  components/vf-design-tokens/vf-design-tokens.config.yml
  components/vf-sass-config/README.md
  components/vf-sass-config/index.scss
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-sass-config/vf-sass-config.config.yml
  components/vf-sass-utilities/vf-sass-utilities.config.yml
  components/vf-utility-classes/vf-utility-classes.config.yml
  tools/component-generator/index.js
  tools/vf-frctl-theme/views/partials/browser/component-list.njk
Labels: Type: Documentation

#551 bug: sass maps in css custom properties
  components/vf-logo/vf-logo.scss
Labels: Type: Bug

#553 changes css:production to not overwrite the style.css with minified css
  tools/gulp-tasks/vf-css.js
Labels: Type: Enhancement, Type: Refactor

#555 Bug: logo fixes
  components/embl-logo/embl-logo.config.yml
  components/embl-logo/embl-logo.njk
  components/embl-logo/embl-logo.scss
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.njk
Labels: Type: Bug, Type: Component or Pattern

#556 Documentation: Improve vf-sass-config documentation
  components/vf-componenet-rollup/index.scss
  components/vf-sass-config/README.md
  components/vf-sass-config/functions/string-replace.scss
  components/vf-sass-config/mixins/_blockquote.scss
  components/vf-sass-config/mixins/_button.scss
  components/vf-sass-config/mixins/_divider.scss
  components/vf-sass-config/mixins/_figure.scss
  components/vf-sass-config/mixins/_helpers.scss
  components/vf-sass-config/mixins/_links.scss
  components/vf-sass-config/mixins/_lists.scss
  components/vf-sass-config/mixins/_margin.scss
  components/vf-sass-config/mixins/_padding.scss
  components/vf-sass-config/mixins/_text-color.scss
  components/vf-sass-config/mixins/_typography.scss
  components/vf-sass-config/mixins/_utility--color.scss
  components/vf-sass-config/mixins/_utility--slide.scss
  components/vf-sass-config/mixins/_utility--spacing.scss
  components/vf-sass-config/mixins/_utility--typography.scss
  components/vf-sass-config/mixins/_vf-mixins.scss
  components/vf-sass-config/mixins/_vf-utility-mixins.scss
  components/vf-sass-config/mixins/vf-disabled.scss
  components/vf-sass-config/variables/_vf-variables.shame.scss
  components/vf-sass-config/variables/vf-global-custom-properties.scss
  components/vf-sass-config/variables/vf-global-variables.scss
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-sass-config/vf-sass-config.config.yml
  components/vf-sass-config/vf-sass-config.njk
  tools/vf-frctl-theme/views/partials/pen/browser.njk
Labels: Type: Documentation

#557 BUG - design tokens not showing in component library
  components/vf-design-tokens/dist/json/vf-font--monospace.ios.json
  components/vf-design-tokens/dist/sass/vf-font--monospace.scss
  components/vf-design-tokens/gulpfile.js
  components/vf-design-tokens/src/vf-design-tokens.config.yml
  components/vf-design-tokens/vf-design-tokens.config.js
  components/vf-design-tokens/vf-design-tokens.config.yml
  components/vf-design-tokens/vf-design-tokens.njk
  components/vf-design-tokens/vf-design-tokens.scss
Labels: Type: Bug

#563 ENHANCEMENT: allow component CSS to proceed
  tools/gulp-tasks/vf-css.js
Labels: Type: Enhancement

#566 FEATURE: Make compiled CSS available as an "asset"
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-assets.js
Labels: Type: Feature

#567 ENHANCEMENT: Do not optimise SVGs on `watch`
  tools/gulp-tasks/vf-assets.js
  tools/gulp-tasks/vf-watch.js
Labels: Type: Enhancement

#571 Deprecated: some vf-button classes
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.scss
  components/vf-deprecated/README.md
  components/vf-deprecated/vf-deprecated.scss
Labels: Compatibility, Type: Component or Pattern

#568 the one where we update the vf-button component
  components/_previews/_preview.njk
  components/vf-banner/vf-banner.js
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.config.yml
  components/vf-button/vf-button.njk
  components/vf-button/vf-button.scss
  components/vf-deprecated/README.md
  components/vf-deprecated/vf-deprecated.scss
  components/vf-sass-config/mixins/_links.scss
  components/vf-tabs/vf-tabs.scss
Labels: Breaking Change, Status: Review Needed, Type: Refactor

#574 Add a "fractal data" build mode
  fractal.js
Labels: Type: Feature

#578 Refactor/vf button
  components/vf-button/vf-button.scss
  components/vf-search/vf-search.scss
  components/vf-summary/vf-summary--job.njk
  components/vf-summary/vf-summary--job.scss
  components/vf-summary/vf-summary.scss
Labels: Status: Review Needed, Type: Refactor

#582 ENHANCEMENT - Optimise npm dependencies
  .npmignore
  package.json
  yarn.lock
Labels: Type: Enhancement
