Repository visual-framework/vf-core, pull requests merged in 2019-01, with the labels that each got.

#123 Support multiple tabs
  components/vf-tabs/vf-tabs.hbs
  components/vf-tabs/vf-tabs.js
Labels: Type: Bug

#146 Update npm-shrinkwrap.json
  npm-shrinkwrap.json
Labels: Type: Bug, Type: Chore

#147 Update gulpfile.js
  gulpfile.js
Labels: Type: Bug

#164 Add "This page was intentionally left blank"
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.scss
  components/embl-content-hub-loader/embl-content-hub-loader.scss
  components/vf-no-js/vf-no-js.scss
  components/vf-summary-container/vf-summary-container.scss
  tools/component-generator/templates/_component.scss
Labels: Type: Documentation

#165 Deprecate GDPR banner
  components/vf-contact/vf-contact.scss
  components/vf-data-protection-banner/README.md
  components/vf-data-protection-banner/vf-data-protection-banner.config.yml
  components/vf-data-protection-banner/vf-data-protection-banner.scss
  components/vf-job-description/vf-job-description.scss
  components/vf-news-item/vf-news-item.scss
  components/vf-snippet/vf-snippet.scss
  components/vf-tag/vf-tag.scss
Labels: Type: Pattern

#167 Add some guidance on JS usage in patterns
  README.md
  tools/component-generator/templates/_component.js
Labels: Type: Documentation

#175 refactors vf-breadcrumbs - breaking change
  components/vf-breadcrumbs/vf-breadcrumbs--with-related.hbs
  components/vf-breadcrumbs/vf-breadcrumbs--with-related.scss
  components/vf-breadcrumbs/vf-breadcrumbs.hbs
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-breadcrumbs/vf-breadcrumbs.variables.scss
  components/vf-core/index.scss
Labels: Type: Enhancement, Type: Refactor

#177 Feature/update embl breadcrumbs lookup
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.hbs
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.scss
  components/vf-core/index.scss
Labels: Type: Pattern, Type: Refactor

#183 Add ability to auto-accept banners
  components/vf-banner/vf-banner--fixed.hbs
  components/vf-banner/vf-banner.js
Labels: Type: Feature

#189 Sync develop to master
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-code-example/vf-code-example.scss
  components/vf-favicon/assets/safari-pinned-tab.svg
  components/vf-sass-config/variables/vf-font--sans.scss
  components/vf-summary/vf-summary--news-has-image.scss
Labels: Type: Chore

#191 fix/vf-banner-style-imports
  components/vf-banner/index.scss
Labels: Type: Bug

#193 Make per-pattern JS more reliable
  components/embl-breadcrumbs-lookup/package.json
  components/embl-conditional-edit/package.json
  components/embl-content-hub-loader/embl-content-hub-loader.js
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  components/embl-content-hub-loader/package.json
  components/vf-banner/vf-banner.js
  components/vf-no-js/package.json
  components/vf-tabs/vf-tabs.js
Labels: Type: Bug, Type: Enhancement

#192 Include varaibale.scss in package.json
  components/embl-content-hub-loader/package.json
  components/vf-banner/index.scss
  components/vf-banner/package.json
  components/vf-box/index.scss
  components/vf-box/package.json
  components/vf-breadcrumbs/index.scss
  components/vf-breadcrumbs/package.json
  components/vf-inlay/package.json
  components/vf-inlay/vf-inlay.scss
  components/vf-summary/package.json
  tools/component-generator/templates/_package.json
Labels: Type: Bug
