Repository visual-framework/vf-core, pull requests merged in 2019-04, with the labels that each got.

#341 HOTFIX - Pass missing param to codeblock extension
  fractal.js
Labels: Type: Bug

#331 Add missing npm files
  components/vf-logo/package-lock.json
  components/vf-logo/package.json
  components/vf-no-js/package.json
Labels: Type: Chore

#343 Modularise fractal config for reuse as `require`
  fractal.js
  gulpfile.js
Labels: Type: Feature

#340 Add notes on versioning of components
  docs/changelog/index.njk
  docs/guidelines/versioning.njk
Labels: Type: Documentation

#346 ENHANCEMENT - vf-core npm optimisations
  .npmignore
  components/vf-componenet-rollup/CHANGELOG.md
  components/vf-componenet-rollup/README.md
  components/vf-componenet-rollup/index.scss
  components/vf-componenet-rollup/package.json
  components/vf-componenet-rollup/scripts.js
  components/vf-core/README.md
  fractal.js
  gulpfile.js
  npm-shrinkwrap.json
  package.json
Labels: Type: Enhancement

#347 Chore/deprecation documentation
  docs/contributing/creating-new-components.njk
  docs/contributing/css.njk
  docs/contributing/deprecating-components.njk
  docs/contributing/global-token-variables.njk
  docs/contributing/index.njk
  docs/contributing/javascript.njk
  docs/contributing/naming.njk
  docs/contributing/writing-and-language.njk
Labels: Type: Documentation

#348 fix/font-component-naming
  components/vf-font-plex-mono/CHANGELOG.md
  components/vf-font-plex-mono/package.json
  components/vf-font-plex-sans/CHANGELOG.md
  components/vf-font-plex-sans/package.json
  components/vf-search/CHANGELOG.md
  components/vf-search/package.json
  npm-shrinkwrap.json
Labels: Type: Bug

#350 fix: npmignore files and version
  .npmignore
  package.json
Labels: Type: Bug

#353 fix: support passing "false"
  fractal.js
Labels: Type: Bug

#352 CHORE - npm file tracking
  tools/component-generator/index.js
  tools/component-generator/templates/_.npmignore
  tools/component-generator/templates/_package.json
Labels: Type: Chore

#338 WIP: updates components to use yaml where possible
  components/vf-activity-group/vf-activity-group.config.yml
  components/vf-activity-group/vf-activity-group.njk
  components/vf-activity-list/vf-activity-list.config.yml
  components/vf-activity-list/vf-activity-list.njk
  components/vf-article-meta-information/vf-article-meta-information.config.yml
  components/vf-article-meta-information/vf-article-meta-information.njk
  components/vf-article-meta-information/vf-article-meta-information.scss
  components/vf-badge/README.md
  components/vf-badge/vf-badge--links.njk
  components/vf-badge/vf-badge--outline.njk
  components/vf-badge/vf-badge--sizes.njk
  components/vf-badge/vf-badge--styles.njk
  components/vf-badge/vf-badge--variants.njk
  components/vf-badge/vf-badge.config.yml
  components/vf-badge/vf-badge.njk
  components/vf-banner/vf-banner.scss
  components/vf-box/vf-box--factoid.njk
  components/vf-box/vf-box--inlay.njk
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.njk
  components/vf-button/vf-button--outline.njk
  components/vf-button/vf-button--variants.njk
  components/vf-button/vf-button.scss
  components/vf-sass-config/mixins/_links.scss
  components/vf-summary/vf-summary--profile.njk
  components/vf-summary/vf-summary.config.yml
  components/vf-text/vf-text.config.yml
  components/vf-text/vf-text.njk
  fractal.js
Labels: Status: In Progress

#357 Optimise gulp dev
  fractal.js
  gulpfile.js
  npm-shrinkwrap.json
Labels: Changelog

#351 Documentation/governance
  docs/contributing/governance.njk
Labels: Changelog, Type: Documentation

#327 Features/markdown filters
  components/vf-componenet-rollup/index.scss
  components/vf-content/README.md
  components/vf-content/vf-content.njk
  components/vf-link/vf-link.config.yml
  fractal.js
  npm-shrinkwrap.json
  package.json
  tools/vf-frctl-extensions/markdown.js
  tools/vf-frctl-theme/src/extensions/markdown.js
  tools/vf-frctl-theme/src/extensions/render.js
  tools/vf-frctl-theme/src/theme.js
Labels: Status: On Hold, Type: Feature, WIP

#363 refactor vf-element components to make use of yaml/nunjucks
  components/vf-blockquote/vf-blockquote.config.yml
  components/vf-blockquote/vf-blockquote.njk
  components/vf-button/vf-button--outline.njk
  components/vf-button/vf-button--sizes.njk
  components/vf-button/vf-button--styles.njk
  components/vf-button/vf-button--variants.njk
  components/vf-button/vf-button.config.yml
  components/vf-button/vf-button.njk
  components/vf-divider/vf-divider.njk
  components/vf-figure/vf-figure.config.yml
  components/vf-figure/vf-figure.njk
  components/vf-heading/vf-heading.config.yml
  components/vf-heading/vf-heading.njk
  components/vf-list/vf-list--inline.njk
  components/vf-list/vf-list--ordered.njk
  components/vf-list/vf-list--unordered.njk
  components/vf-list/vf-list.config.yml
  components/vf-list/vf-list.njk
  components/vf-logo/vf-logo--responsive.njk
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.njk
  components/vf-text/vf-text.config.yml
  components/vf-text/vf-text.njk
  components/vf-text/vf-text.scss
Labels: Status: Review Needed, Type: Refactor

#342 Add dynamic sass imports
  components/vf-componenet-rollup/index.scss
  gulpfile.js
  npm-shrinkwrap.json
  package.json
Labels: Type: Feature

#365 updates figure and logo to make use of | path correctly so it works
  components/vf-box/vf-box.njk
  components/vf-figure/vf-figure.njk
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.njk
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#366 Use develop CSS
  components/embl-boilerplate-page/embl-boilerplate-page.njk
  components/embl-group-page/embl-group-page--contact.njk
  components/embl-group-page/embl-group-page.njk
  components/embl-subsite-page/embl-subsite-page.njk
  components/vf-boilerplate-page/vf-boilerplate-page.njk
Labels: Type: Bug

#367 fix: embl-grid-and-breadcrumbs
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.njk
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.scss
  components/vf-breadcrumbs/vf-breadcrumbs.scss
Labels: Type: Bug

#371 Fixes/inlay header errors
  components/embl-group-page/embl-group-page.njk
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-breadcrumbs/vf-breadcrumbs.variables.scss
  components/vf-global-header/vf-global-header.scss
  components/vf-masthead/vf-masthead.scss
Labels: Status: Review Needed, Type: Bug

#372 refactor vf-blocks to use yaml and nunjucks where possible/sensible
  components/vf-breadcrumbs/vf-breadcrumbs--with-related.njk
  components/vf-breadcrumbs/vf-breadcrumbs.config.yml
  components/vf-breadcrumbs/vf-breadcrumbs.njk
  components/vf-discussion/vf-discussion.config.yml
  components/vf-discussion/vf-discussion.njk
  components/vf-global-header/vf-global-header.config.yml
  components/vf-global-header/vf-global-header.njk
  components/vf-link-list/vf-link-list--has-images.njk
  components/vf-link-list/vf-link-list--tight.njk
  components/vf-link-list/vf-link-list.config.yml
  components/vf-link-list/vf-link-list.njk
  components/vf-navigation/vf-navigation--additional.njk
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--global.njk
  components/vf-navigation/vf-navigation--main.njk
  components/vf-navigation/vf-navigation.config.yml
  components/vf-navigation/vf-navigation.njk
  components/vf-page-header/vf-page-header.config.yml
  components/vf-page-header/vf-page-header.njk
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
  components/vf-summary/vf-summary--profile.njk
  components/vf-summary/vf-summary.config.yml
  components/vf-tabs/vf-tabs.config.yml
  components/vf-tabs/vf-tabs.njk
  components/vf-video/vf-video.config.yml
  components/vf-video/vf-video.njk
  npm-shrinkwrap.json
Labels: Status: In Progress, Type: Enhancement, Type: Refactor

#375 ContentHub layout issues
  components/embl-content-hub-loader/embl-content-hub-loader.scss
  components/vf-componenet-rollup/index.scss
Labels: Type: Bug
