Repository visual-framework/vf-core, pull requests merged in 2019-11, with the labels that each got.

#644 ENHANCEMENT: Renovate bot configuration
  components/vf-design-tokens/yarn.lock
  renovate.json
Labels: Priority: Medium, Type: Enhancement

#554 resolves some small responsive issues for group pages (and components)
  components/embl-grid/embl-grid.scss
  components/vf-button/vf-button.scss
  components/vf-footer/vf-footer.scss
  components/vf-inlay/vf-inlay.scss
  components/vf-inlay/vf-inlay.variables.scss
  components/vf-masthead/vf-masthead--supports.scss
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/vf-navigation--main.scss
  components/vf-summary/vf-summary--news.scss
Labels: Priority: High, Type: Bug, Type: Component or Pattern

#646 Documentation: utility class docs
  components/vf-utility-classes/vf-u-text.scss
  components/vf-utility-classes/vf-utility-classes.config.yml
  components/vf-utility-classes/vf-utility-classes.njk
Labels: Type: Documentation

#638 Feauture/utility classes
  components/vf-sass-utilities/README.md
  components/vf-sass-utilities/vf-sass-utilities.config.yml
  components/vf-sass-utilities/vf-sass-utilities.scss
  components/vf-utility-classes/README.md
  components/vf-utility-classes/vf-u-float.scss
  components/vf-utility-classes/vf-u-screen-reader.scss
  components/vf-utility-classes/vf-u-text.scss
  components/vf-utility-classes/vf-utility-classes--background.njk
  components/vf-utility-classes/vf-utility-classes--border.njk
  components/vf-utility-classes/vf-utility-classes--float.njk
  components/vf-utility-classes/vf-utility-classes.config.yml
  components/vf-utility-classes/vf-utility-classes.njk
  components/vf-utility-classes/vf-utility-classes.scss
Labels: Priority: Medium, Status: WIP, Type: Feature

#647 BUG: rennovate-sourceurl
  renovate.json
Labels: Type: Bug

#648 BUG - placeholder-opacity-ff
  components/vf-form/vf-form__input/vf-form__input.scss
Labels: Type: Bug

#650 Chore: Remove embl-subsite-page boilerplate
  components/embl-subsite-page/.npmignore
  components/embl-subsite-page/CHANGELOG.md
  components/embl-subsite-page/README.md
  components/embl-subsite-page/embl-subsite-page.config.yml
  components/embl-subsite-page/embl-subsite-page.js
  components/embl-subsite-page/embl-subsite-page.njk
  components/embl-subsite-page/index.scss
  components/embl-subsite-page/package.json
Labels: Type: Chore

#663 Bug: update usage of class names for vf-utility-classes
  components/embl-logo/embl-logo.njk
  components/vf-form/vf-form__input/vf-form__input.njk
  components/vf-form/vf-form__item/vf-form__item.njk
  components/vf-form/vf-form__label/vf-form__label.njk
  components/vf-form/vf-form__textarea/vf-form__textarea.njk
  components/vf-logo/vf-logo.njk
  components/vf-pagination/vf-pagination.njk
  components/vf-sass-utilities/README.md
  components/vf-sass-utilities/_vf-screen-reader.scss
  components/vf-sass-utilities/vf-sass-utilities.scss
  components/vf-search/vf-search--inline.njk
  components/vf-search/vf-search.njk
  components/vf-summary/README.md
  components/vf-utility-classes/vf-utility-classes.njk
Labels: Priority: Medium, Type: Bug, Type: Documentation

#660 COMPONENT - ebi header footer
  components/ebi-header-footer/.npmignore
  components/ebi-header-footer/CHANGELOG.md
  components/ebi-header-footer/README.md
  components/ebi-header-footer/ebi-header-footer--embl-selector.scss
  components/ebi-header-footer/ebi-header-footer--footer.scss
  components/ebi-header-footer/ebi-header-footer--form.scss
  components/ebi-header-footer/ebi-header-footer--header.scss
  components/ebi-header-footer/ebi-header-footer--layout.scss
  components/ebi-header-footer/ebi-header-footer--utility.scss
  components/ebi-header-footer/ebi-header-footer.config.yml
  components/ebi-header-footer/ebi-header-footer.js
  components/ebi-header-footer/ebi-header-footer.njk
  components/ebi-header-footer/ebi-header-footer.scss
  components/ebi-header-footer/ebi-header-footer.variables.scss
  components/ebi-header-footer/index.scss
  components/ebi-header-footer/package.json
  components/vf-componenet-rollup/index.scss
Labels: Type: Component or Pattern

#664 the one where we introduce the start of vf-hero
  components/vf-componenet-rollup/index.scss
  components/vf-hero/.npmignore
  components/vf-hero/CHANGELOG.md
  components/vf-hero/README.md
  components/vf-hero/assets/vf-intro-group.png
  components/vf-hero/index.scss
  components/vf-hero/package.json
  components/vf-hero/vf-hero--example.njk
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.js
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
  components/vf-hero/vf-hero.variables.scss
  components/vf-lens/.npmignore
  components/vf-lens/CHANGELOG.md
  components/vf-lens/README.md
  components/vf-lens/index.scss
  components/vf-lens/package.json
  components/vf-lens/vf-lens.config.yml
  components/vf-lens/vf-lens.js
  components/vf-lens/vf-lens.njk
  components/vf-lens/vf-lens.scss
  components/vf-lens/vf-lens.variables.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern
