Repository visual-framework/vf-core, pull requests merged in 2020-09, with the labels that each got.

#1078 🐛 the one that fixes a couple of CSS grid issues with embl-grid.
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.scss
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1076 the one that updates max-width in a few places and sets context for logos
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.scss
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.config.yml
  components/vf-global-header/vf-global-header.njk
  components/vf-global-header/vf-global-header.scss
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.scss
  components/vf-logo/CHANGELOG.md
  components/vf-logo/vf-logo.njk
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--main.scss
  tools/vf-frctl-theme/CHANGELOG.md
  tools/vf-frctl-theme/dist/css/default.css
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Refactor

#1080 chore: add-favicon-social-meta-to-library
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/src/site/_includes/layouts/base.njk
Labels: Type: Chore

#1079 chore: vf-card conditional title and alt example
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
Labels: Type: Chore, Type: Documentation, Type: Enhancement

#1081 💄 the one that removes inline padding on the footer
  components/vf-footer/CHANGELOG.md
  components/vf-footer/vf-footer.scss
Labels: Priority: Low, Status: Feedback Needed, Type: Refactor

#1069 component: vf-location-nearest
  components/vf-componenet-rollup/scripts.js
  components/vf-location-nearest/.npmignore
  components/vf-location-nearest/CHANGELOG.md
  components/vf-location-nearest/README.md
  components/vf-location-nearest/index.scss
  components/vf-location-nearest/package.json
  components/vf-location-nearest/vf-location-nearest.config.yml
  components/vf-location-nearest/vf-location-nearest.js
  components/vf-location-nearest/vf-location-nearest.njk
  components/vf-location-nearest/vf-location-nearest.scss
  components/vf-location-nearest/vf-location-nearest.variables.scss
Labels: Type: Component or Pattern

#1082 💄 the moves the inline padding around so it matches layout
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug, Type: Enhancement

#1083 bug: race condition in vf-build
  tools/vf-core/gulp-tasks/vf-build.js
Labels: Priority: High, Type: Bug

#1084 💄 the one that updates :visited colour for links in text
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1086 💄 the one that fixes the text color on hover when the button has secondary theming
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#1087 🐛 The one that fixes bug with image height in Safari
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Enhancement

#1088 🎨 The one that adds the `loading` attribute to component images
  components/vf-article-meta-information/CHANGELOG.md
  components/vf-article-meta-information/vf-article-meta-information.njk
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.njk
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.njk
  components/vf-discussion/CHANGELOG.md
  components/vf-discussion/vf-discussion.njk
  components/vf-figure/CHANGELOG.md
  components/vf-figure/vf-figure.njk
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero--example.njk
  components/vf-logo/CHANGELOG.md
  components/vf-logo/vf-logo.njk
  components/vf-profile/CHANGELOG.md
  components/vf-profile/vf-profile.njk
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--has-image.njk
  components/vf-summary/vf-summary--news-has-image.njk
  components/vf-summary/vf-summary--profile.njk
  components/vf-video-teaser/CHANGELOG.md
  components/vf-video-teaser/vf-video-teaser.njk
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1090 chore: analytics-image-handling
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Type: Chore

#1089 ✨ the one that adds a new layout component for vertical rhythm / flow
  components/vf-componenet-rollup/index.scss
  components/vf-stack/.npmignore
  components/vf-stack/CHANGELOG.md
  components/vf-stack/README.md
  components/vf-stack/index.scss
  components/vf-stack/package.json
  components/vf-stack/vf-stack.config.yml
  components/vf-stack/vf-stack.njk
  components/vf-stack/vf-stack.scss
  components/vf-stack/vf-stack.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#1092 enhancement: catch cases where content-hub has nothing to do
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
Labels: Type: Enhancement

#1094 bug: vf-breadcrumbs with related url
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-breadcrumbs/vf-breadcrumbs--with-related.njk
Labels: Priority: High, Type: Bug

#1095 💄 the one that updates all the things for the vf-box component
  components/vf-box/CHANGELOG.md
  components/vf-box/README.md
  components/vf-box/vf-box--factoid.scss
  components/vf-box/vf-box--inlay.scss
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.njk
  components/vf-box/vf-box.scss
  components/vf-componenet-rollup/index.scss
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-zindex.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-zindex.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-zindex.map.scss
  components/vf-design-tokens/src/maps/vf-zindex.yml
  components/vf-inlay/vf-inlay.njk
  components/vf-stack/vf-stack.njk
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1096 ehnancement: search-template
  components/vf-search/CHANGELOG.md
  components/vf-search/vf-search--inline.njk
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
Labels: Type: Enhancement

#1098 bug: vf-box specificity
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.scss
Labels: Priority: Low, Type: Bug

#1099 💄 the one that fixes the `-link` bug where it takes over the whole page
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.njk
  components/vf-box/vf-box.scss
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1097 enhancement: search default
  components/vf-search/CHANGELOG.md
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
Labels: Type: Enhancement

#1104 🐛 the one that updates the $global-page-max-width variable so it matches the max-width of 81.25rem
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-global-variables.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1103 💄 the one that makes the sidebar in `embl-grid` a sidebar sooner.
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.njk
  components/embl-grid/embl-grid.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#1101 🎨 the one that improves `vf-summary--has-image`
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--has-image.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1100 🔥 the one that removes erroneous 'component' that was give console log issues
  components/vf-stack/vf-stack.config.yml
Labels: Priority: Low, Status: Review Needed, Type: Bug

#1102 Feature: blog updates
  PUBLISHING.md
  README.md
  package.json
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/eleventy.js
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/_includes/layouts/post.njk
  tools/vf-component-library/src/site/developing/guidelines/user-base.njk
  tools/vf-component-library/src/site/feed.njk
  tools/vf-component-library/src/site/posts/sample-post.md
  tools/vf-component-library/src/site/updates.njk
  tools/vf-component-library/src/site/updates/2020-09-09-component-updates.md
  tools/vf-component-library/src/site/updates/2020-09-10-component-updates.md
  tools/vf-component-library/src/site/updates/2020-09-11-communicating-more.md
Labels: Type: Documentation

#1106 enhancement: prevent recursive breadcrumbs
  components/embl-breadcrumbs-lookup/CHANGELOG.md
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
Labels: Type: Enhancement

#1108 chore: mon-repo-link
  PUBLISHING.md
  README.md
  tools/vf-component-library/src/site/developing/components/updating-a-component.njk
  tools/vf-core/README.md
Labels: Type: Chore, Type: Documentation

#1109 docs: vf-search-client-side
  components/vf-search-client-side/CHANGELOG.md
  components/vf-search-client-side/README.md
  components/vf-search-client-side/vf-search-client-side.config.yml
Labels: Type: Documentation

#1112 Update search-results.njk
  tools/vf-component-library/src/site/patterns/search-results.njk
  tools/vf-component-library/src/site/search.njk
Labels: Type: Component or Pattern

#1113 🐛 the one where we add `-webkit-appearance: none;` as needed
  components/ebi-header-footer/CHANGELOG.md
  components/ebi-header-footer/ebi-header-footer--form.scss
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.scss
  components/vf-form/vf-form__input/CHANGELOG.md
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__select/CHANGELOG.md
  components/vf-form/vf-form__select/vf-form__select.scss
  components/vf-form/vf-form__textarea/CHANGELOG.md
  components/vf-form/vf-form__textarea/vf-form__textarea.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/mixins/_button.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1123 💄 the one that adds search input type and styles the cancel button
  components/vf-form/vf-form__input/CHANGELOG.md
  components/vf-form/vf-form__input/vf-form__input.njk
  components/vf-form/vf-form__input/vf-form__input.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1124 💄 the one that helps make cards look like cards on a page with a little box shadow.
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1135 Bug: Fix console verbose logging
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Type: Bug

#1137 enhancement: vf-banner don't block content
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.js
Labels: Type: Enhancement
