Repository visual-framework/vf-core, pull requests merged in 2020-06, with the labels that each got.

#940 the one that makes the hero snappy
  components/vf-hero/CHANGELOG.md
  components/vf-hero/assets/jarallax.js
  components/vf-hero/vf-hero--example.njk
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
Labels: Status: Review Needed, Type: Enhancement

#948 should fix the image handling error, plus some other little fixes
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
Labels: Status: Review Needed, Type: Bug

#949 vf_hero_link should be vf_hero_href
  components/vf-hero/vf-hero.config.yml
Labels: Type: Bug

#951 the one where we are making the hero component better, again, again.
  components/vf-hero/CHANGELOG.md
  components/vf-hero/README.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
Labels: Priority: Medium, Status: Review Needed

#952 the one that brings the vf-footer styling back a z-index layer
  components/vf-footer/vf-footer.scss
Labels: Priority: Medium, Status: Feedback Needed, Type: Bug

#958 the last one to fix vf-summary--profile
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--profile.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#962 chore: refresh yarn.lock
  yarn.lock
Labels: Priority: Low, Type: Chore

#964 the one that makes the background image width the same as the content
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#954 the one that only slightly changes tabs
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/vf-tabs.config.yml
  components/vf-tabs/vf-tabs.njk
  components/vf-tabs/vf-tabs.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#966 the one that changes commit to commit and push
  PUBLISHING.md
Labels: Priority: Low, Type: Bug, Type: Documentation

#967 Bug: breakpoint map missing from vf-variables.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-variables.scss
Labels: Priority: High, Type: Bug

#970 bug: contentHub no results detection
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
Labels: Priority: High, Type: Bug

#969 the one that tidies up tabs label in fractal theme
  tools/vf-frctl-theme/views/partials/pen/preview.njk
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#971 Refactor/vf logo
  components/embl-logo/CHANGELOG.md
  components/embl-logo/embl-logo.scss
  components/vf-logo/CHANGELOG.md
  components/vf-logo/vf-logo.njk
  components/vf-logo/vf-logo.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#972 The one that tidies up the global header a little more
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.njk
  components/vf-global-header/vf-global-header.scss
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--global.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#982 the one that fixes the misspelling of tertiary
  components/vf-banner/README.md
Labels: Priority: Low, Status: Review Needed, Type: Bug

#981 the one that removes wrapper from global-header in fractal theme
  tools/vf-frctl-theme/views/partials/header.njk
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#980 the one that removes word-spacing from the author-name
  components/vf-article-meta-information/CHANGELOG.md
  components/vf-article-meta-information/vf-article-meta-information.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#979 the one that makes lists fit inside of the vf-content block
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#977 The one that makes the GDRP banner work in IE 11 better
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.scss
  components/vf-banner/vf-banner.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#975 the one where we create a new vf-profile component
  components/vf-componenet-rollup/index.scss
  components/vf-profile/.npmignore
  components/vf-profile/CHANGELOG.md
  components/vf-profile/README.md
  components/vf-profile/assets/vf-icon--avatar.svg
  components/vf-profile/index.scss
  components/vf-profile/package.json
  components/vf-profile/vf-profile.config.yml
  components/vf-profile/vf-profile.js
  components/vf-profile/vf-profile.njk
  components/vf-profile/vf-profile.scss
  components/vf-profile/vf-profile.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern

#986 Fix hiding of default variant
  components/vf-profile/CHANGELOG.md
  components/vf-profile/vf-profile.config.yml
Labels: Priority: Low, Type: Bug

#991 the one that tidies the `vf-banner` up a little bit
  components/vf-banner/README.md
  components/vf-banner/vf-banner--alerts.scss
  components/vf-banner/vf-banner.njk
  components/vf-banner/vf-banner.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#992 Bug/vf hero inlay
  components/vf-banner/vf-banner--alerts.scss
  components/vf-hero/vf-hero.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#985 the one that refactors vf-card so it works better in vf-11ty
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/vf-card-container.config.yml
  components/vf-card-container/vf-card-container.scss
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
Labels: Priority: High, Status: Review Needed, Type: Refactor

#988 the one that brings relative paths back
  components/vf-componenet-rollup/CHANGELOG.md
  components/vf-componenet-rollup/index.scss
  components/vf-font-plex-mono/vf-font-plex-mono.scss
  components/vf-font-plex-sans/vf-font-plex-sans.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/index.scss
  components/vf-sass-config/package.json
  components/vf-sass-config/variables/vf-global-variables.scss
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-sass-utilities/CHANGELOG.md
  components/vf-sass-utilities/_vf-screen-reader.scss
  tools/gulp-tasks/_gulp_rollup.js
Labels: Priority: High, Status: Review Needed, Type: Refactor

#993 the one that adds a changelog, that's it. That's the commit.
  components/vf-hero/CHANGELOG.md
Labels: Priority: Low, Type: Bug

#994 Bug/changelogs
  components/vf-font-plex-mono/CHANGELOG.md
  components/vf-font-plex-sans/CHANGELOG.md
  tools/vf-frctl-theme/CHANGELOG.md
Labels: Priority: Low, Type: Bug

#989 The one that includes a 'starter kit' of Sass files
  components/vf-sass-starter/.npmignore
  components/vf-sass-starter/CHANGELOG.md
  components/vf-sass-starter/README.md
  components/vf-sass-starter/index.scss
  components/vf-sass-starter/package-lock.json
  components/vf-sass-starter/package.json
  components/vf-sass-starter/vf-sass-starter.config.yml
  components/vf-sass-starter/vf-sass-starter.njk
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern

#995 the one that fixes the bug making tabs really large
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/vf-tabs.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#996 the one that fixes the weird layout bugs in the fractal theme
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/index.scss
  tools/vf-frctl-theme/CHANGELOG.md
  tools/vf-frctl-theme/dist/css/default.css
Labels: Priority: High, Status: Review Needed, Type: Bug

#984 the one that hides some files from the documentation for a component.
  fractal.js
Labels: Priority: Low, Status: Review Needed, Type: Documentation

#999 fixes for intense variation
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1000 the one that lets background images work with full bleed
  components/vf-u-fullbleed/CHANGELOG.md
  components/vf-u-fullbleed/vf-u-fullbleed.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#1001 the one that gets the Sass starter working 'as expected'
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-global-variables.scss
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-sass-starter/CHANGELOG.md
  components/vf-sass-starter/index.scss
  components/vf-sass-starter/package.json
Labels: Priority: High, Status: Review Needed, Type: Bug

#1002 the one that updates the version number in vf-global-header
  components/vf-global-header/CHANGELOG.md
Labels: Priority: High, Status: Review Needed, Type: Bug
