Repository visual-framework/vf-core, pull requests merged in 2020-11, with the labels that each got.

#1209 The one that gets the logos 'on point'
  components/embl-logo/CHANGELOG.md
  components/embl-logo/embl-logo.scss
  components/vf-logo/CHANGELOG.md
  components/vf-logo/vf-logo.scss
Labels: Priority: Low, Status: Review Needed, Type: Changelog, Type: Refactor

#1214 🐛 the one that corrects where CSS custom property is defined for variants
  components/vf-cluster/CHANGELOG.md
  components/vf-cluster/vf-cluster.scss
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Component or Pattern

#1215 fixes bug on hover of link and easy variant
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug, Type: Changelog, Type: Component or Pattern

#1213 Docs: consultation process and roadmap
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/about/consultation.njk
  tools/vf-component-library/src/site/about/faq.njk
  tools/vf-component-library/src/site/about/index.njk
  tools/vf-component-library/src/site/about/roadmap.njk
  tools/vf-component-library/src/site/developing/guidelines/governance.njk
Labels: Type: Documentation

#1217 🐛 The one that fixes Sass map interpolation error
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-global-custom-properties.scss
Labels: Priority: High, Status: Complete, Status: Feedback Needed, Type: Bug, Type: Changelog

#1221 Bug: fixes vf-inlay typos
  components/vf-inlay/CHANGELOG.md
  components/vf-inlay/vf-inlay.scss
Labels: Priority: High, Type: Bug

#1222 Chore: JS linting
  components/embl-breadcrumbs-lookup/CHANGELOG.md
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-conditional-edit/CHANGELOG.md
  components/embl-conditional-edit/embl-conditional-edit.js
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  components/embl-content-hub-loader/embl-content-hub-loader__html-imports.js
  components/embl-notifications/CHANGELOG.md
  components/embl-notifications/embl-notifications.js
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.js
  components/vf-location-nearest/CHANGELOG.md
  components/vf-location-nearest/vf-location-nearest.js
  components/vf-search-client-side/CHANGELOG.md
  components/vf-search-client-side/vf-search-client-side.js
  components/vf-show-more/CHANGELOG.md
  components/vf-show-more/vf-show-more.js
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/vf-tabs.js
  components/vf-tree/CHANGELOG.md
  components/vf-tree/vf-tree.js
Labels: Type: Chore

#1225 docs: update-roadmap
  .vscode/settings.json
  tools/vf-component-library/src/site/about/faq.njk
  tools/vf-component-library/src/site/about/index.njk
  tools/vf-component-library/src/site/about/roadmap.njk
  tools/vf-component-library/src/site/updates.njk
  tools/vf-component-library/src/site/updates/2020-11-10-consulting-and-roadmap.njk
Labels: Type: Documentation

#1227 Bug: vf-show-more, vf-banner
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.js
  components/vf-show-more/CHANGELOG.md
  components/vf-show-more/vf-show-more.js
Labels: Type: Bug

#1234 Bug: Issue when tracking image interactions
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Type: Bug

#1235 bug: in vf-intro don't force styles on vf components
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.scss
Labels: Type: Bug

#1241 the one that removes the JS dependency for vf-hero--intense
  components/vf-hero/CHANGELOG.md
  components/vf-hero/assets/jarallax.js
  components/vf-hero/vf-hero.njk
Labels: Priority: Critical, Status: Review Needed, Type: Bug, Type: Refactor

#1247 Docs: getting started the VF's npm components
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/_includes/layouts/developing.njk
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/_includes/layouts/tokens.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/design-tokens/breakpoints.njk
  tools/vf-component-library/src/site/design-tokens/colours.njk
  tools/vf-component-library/src/site/design-tokens/index.njk
  tools/vf-component-library/src/site/design-tokens/spacing.njk
  tools/vf-component-library/src/site/design-tokens/theming.njk
  tools/vf-component-library/src/site/design-tokens/typography.njk
  tools/vf-component-library/src/site/developing/components/components.11tydata.json
  tools/vf-component-library/src/site/developing/components/creating-new-components.njk
  tools/vf-component-library/src/site/developing/components/deprecating-components.njk
  tools/vf-component-library/src/site/developing/components/updating-a-component.njk
  tools/vf-component-library/src/site/developing/components/what-is-a-component.njk
  tools/vf-component-library/src/site/developing/getting-started/code-of-conduct.njk
  tools/vf-component-library/src/site/developing/getting-started/getting-started.11tydata.json
  tools/vf-component-library/src/site/developing/getting-started/naming.njk
  tools/vf-component-library/src/site/developing/getting-started/pull-requests.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/developing/getting-started/structure.njk
  tools/vf-component-library/src/site/developing/guidelines/css.njk
  tools/vf-component-library/src/site/developing/guidelines/governance.njk
  tools/vf-component-library/src/site/developing/guidelines/guidelines.11tydata.json
  tools/vf-component-library/src/site/developing/guidelines/javascript.njk
  tools/vf-component-library/src/site/developing/guidelines/user-base.njk
  tools/vf-component-library/src/site/developing/guidelines/versioning.njk
  tools/vf-component-library/src/site/developing/index.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/troubleshooting/index.njk
Labels: Type: Documentation

#1245 🐛 bug: css compilation location readout
  tools/vf-core/CHANGELOG.md
  tools/vf-core/gulp-tasks/vf-css.js
Labels: Type: Bug

#1249 feat: export vfGaTrackInteraction (#1248)
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Status: Review Needed, Type: Feature

#1254 Docs: improve getting started
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/about/faq.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/index.njk
  tools/vf-component-library/src/site/troubleshooting/index.njk
Labels: Type: Documentation

#1255 The one that refactors, enhances, and starts to deprecate some things for the vf-card.
  components/vf-card/CHANGELOG.md
  components/vf-card/README.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Enhancement, Type: Refactor

#1256 the one that removes the max-width, which I thought I managed to get in before.
  components/vf-card/vf-card.scss
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1219 The one that refactors the vf-hero quite a lot
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-spacing.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-spacing.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-spacing.map.scss
  components/vf-design-tokens/src/maps/vf-spacing.yml
  components/vf-hero/CHANGELOG.md
  components/vf-hero/README.md
  components/vf-hero/vf-hero--example.njk
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
  components/vf-u-fullbleed/CHANGELOG.md
  components/vf-u-fullbleed/vf-u-fullbleed.scss
Labels: Priority: High, Status: Review Needed, Type: Breaking Change, Type: Refactor

#1258 The one that updates spacing and color functions
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/functions/_set-color.scss
  components/vf-sass-config/functions/_set-spacing.scss
  components/vf-sass-config/functions/vf-functions.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1259 enhancement: multiple-vf-show-more
  components/vf-show-more/CHANGELOG.md
  components/vf-show-more/README.md
  components/vf-show-more/vf-show-more.js
  components/vf-show-more/vf-show-more.njk
  components/vf-show-more/vf-show-more.scss
Labels: Type: Enhancement

#1260 Fix: update and optimise vf core install
  .github/workflows/nodejs.yml
  .gitlab-ci.yml
  package.json
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/templates/notice-boilerplate.njk
  tools/vf-component-library/src/site/troubleshooting/index.njk
  tools/vf-core/package.json
  yarn.lock
Labels: Type: Bug, Type: Enhancement

#1263 fix: vf-sass-config import order
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/index.scss
Labels: Priority: High, Type: Bug

#1265 the one that makes small tweaks to the vf-box defaults
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1266 the one that makes some small tweaks to various summary variants
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--event.scss
  components/vf-summary/vf-summary--news.scss
  components/vf-summary/vf-summary.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1264 the one that adds option to make the heading a link using nunjucks and yaml
  components/vf-hero/CHANGELOG.md
  components/vf-hero/README.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.njk
Labels: Priority: Low, Status: Feedback Needed, Type: Bug

#1267 the one that fixes tiny transitional bug with card titles
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1268 the one that adds a max-content width so shorter titles
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1269 the one that fixes bug where the Sass was being printed for custom property
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-global-custom-properties.scss
Labels: Priority: Critical, Type: Bug

#1270 The one that fixes a couple of issues for the vf-hero
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
Labels: Priority: High, Status: Review Needed, Type: Bug
