Repository visual-framework/vf-core, pull requests merged in 2020-12, with the labels that each got.

#1273 the one that fixes missing context items
  components/vf-hero/vf-hero.njk
Labels: Priority: High, Status: Review Needed, Type: Bug

#1275 the one that fixes SVG used with within the `vf-hero` link
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1276 Chore: change vf-banner dismiss button default
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.js
Labels: Type: Chore

#1280 Enhancement: vf-search refinements
  components/vf-search/CHANGELOG.md
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
  components/vf-search/vf-search.scss
Labels: Type: Enhancement

#1278 Enhancement: create reusable tooling for react
  .eslintrc.js
  .vscode/settings.json
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.react.js
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.react.js
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/README.md
  tools/vf-component-generator/index.js
  tools/vf-component-generator/templates/_component.js
  tools/vf-component-generator/templates/_component.react.js
  tools/vf-component-library/eleventy.js
  tools/vf-component-library/src/site/_includes/layouts/components.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-extensions-react/CHANGELOG.md
  tools/vf-extensions-react/LICENSE
  tools/vf-extensions-react/README.md
  tools/vf-extensions-react/assets/nunjucks-slim.js
  tools/vf-extensions-react/package.json
  tools/vf-extensions-react/vf-extensions-react.config.yml
  tools/vf-extensions-react/vf-extensions-react.js
  tools/vf-extensions-react/vf-extensions-react.njk
Labels: Type: Enhancement

#1291 Use react-dom-fragment to return html fragments
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.react.js
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.react.js
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/templates/_component.react.js
  tools/vf-component-library/src/site/_includes/layouts/components.njk
  tools/vf-core/gulp-tasks/vf-templates-precompile.js
  tools/vf-extensions-react/CHANGELOG.md
  tools/vf-extensions-react/README.md
  tools/vf-extensions-react/assets/nunjucks-slim.js
  tools/vf-extensions-react/package.json
  tools/vf-extensions-react/vf-extensions-react.js
Labels: Type: Enhancement

#1293 Documentation: assorted updates
  .vscode/extensions.json
  components/vf-grid/README.md
  tools/vf-component-library/src/site/_includes/layouts/components.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/troubleshooting/index.njk
Labels: Type: Documentation

#1279 Chore: typo in npm install command
  components/embl-conditional-edit/README.md
  components/embl-content-hub-loader/README.md
  components/vf-article-meta-information/README.md
  components/vf-discussion/README.md
  components/vf-inlay/README.md
  components/vf-intro/README.md
  components/vf-lede/README.md
  components/vf-pagination/README.md
  components/vf-search/README.md
Labels: Type: Chore, Type: Documentation

#1298 Documentation: add guidance section
  .vscode/settings.json
  components/vf-button/vf-button.react.js
  components/vf-card/vf-card.react.js
  components/vf-show-more/vf-show-more.js
  tools/vf-component-generator/templates/_component.react.js
  tools/vf-component-library/gulpfile.js
  tools/vf-component-library/src/site/_data/blocks.json
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/_includes/vf-core-components
  tools/vf-component-library/src/site/_includes/vf-core-components.readme.md
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/developing/components/creating-new-components.njk
  tools/vf-component-library/src/site/developing/components/deprecating-components.njk
  tools/vf-component-library/src/site/developing/components/updating-a-component.njk
  tools/vf-component-library/src/site/developing/components/what-is-a-component.njk
  tools/vf-component-library/src/site/developing/getting-started/naming.njk
  tools/vf-component-library/src/site/developing/getting-started/structure.njk
  tools/vf-component-library/src/site/developing/guidelines/css.njk
  tools/vf-component-library/src/site/developing/guidelines/governance.njk
  tools/vf-component-library/src/site/developing/guidelines/javascript.njk
  tools/vf-component-library/src/site/developing/guidelines/user-base.njk
  tools/vf-component-library/src/site/developing/guidelines/versioning.njk
  tools/vf-component-library/src/site/developing/index.njk
  tools/vf-component-library/src/site/guidance/browser-support.md
  tools/vf-component-library/src/site/guidance/components-and-patterns.md
  tools/vf-component-library/src/site/guidance/creating-components.md
  tools/vf-component-library/src/site/guidance/css-and-sass.md
  tools/vf-component-library/src/site/guidance/discussing-the-vf.njk
  tools/vf-component-library/src/site/guidance/image-handling.md
  tools/vf-component-library/src/site/guidance/index.njk
  tools/vf-component-library/src/site/guidance/javascript.md
  tools/vf-component-library/src/site/guidance/language-british-american-english.md
  tools/vf-component-library/src/site/guidance/user-base.md
  tools/vf-component-library/src/site/guidance/versioning-and-component-interoperability.md
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/index.njk
  tools/vf-extensions-react/README.md
Labels: Type: Documentation

#1300 Chore: update changelog guidance
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/templates/_CHANGELOG.md
  tools/vf-component-library/src/site/guidance/creating-components.md
  tools/vf-component-library/src/site/guidance/discussing-the-vf.njk
  tools/vf-component-library/src/site/guidance/versioning-and-component-interoperability.md
Labels: Type: Chore, Type: Documentation

#1302 The one that makes components stack (a little)
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.scss
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--main.scss
Labels: Priority: Medium, Status: Feedback Needed, Type: Refactor

#1304 The one that makes the `vf-figure` responsive.
  components/vf-figure/CHANGELOG.md
  components/vf-figure/README.md
  components/vf-figure/vf-figure.scss
Labels: Priority: Low, Status: Feedback Needed, Type: Component or Pattern, Type: Refactor

#1309 Bug: unnecessary Eleventy rebuilds on Sass and JS updates
  tools/vf-component-library/.gitignore
  tools/vf-extensions/11ty/vfEleventyCommonPlugin.js
  tools/vf-extensions/CHANGELOG.md
  tools/vf-extensions/gulp-tasks/gulp-eleventy.js
Labels: Type: Bug

#1308 Bug: fix vf-tabs display
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/README.md
  components/vf-tabs/vf-tabs.config.yml
  components/vf-tabs/vf-tabs.js
Labels: Type: Bug

#1306 Bug: missing imports in component index.scss files
  components/vf-activity-group/CHANGELOG.md
  components/vf-activity-group/index.scss
  components/vf-font-plex-mono/CHANGELOG.md
  components/vf-font-plex-mono/index.scss
  components/vf-font-plex-sans/CHANGELOG.md
  components/vf-font-plex-sans/index.scss
  components/vf-intro/CHANGELOG.md
  components/vf-intro/index.scss
  components/vf-link-list/CHANGELOG.md
  components/vf-link-list/index.scss
  components/vf-page-header/CHANGELOG.md
  components/vf-page-header/index.scss
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/index.scss
Labels: Type: Bug

#1310 bug: embl-content-hub-loader results in errors in some conditions
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
Labels: Type: Bug

#1305 enhancement: drop cssnano for native minification
  tools/vf-core/CHANGELOG.md
  tools/vf-core/gulp-tasks/vf-css.js
  tools/vf-sass-compilation/CHANGELOG.md
  tools/vf-sass-compilation/package.json
Labels: Type: Bug, Type: Enhancement
