Repository visual-framework/vf-core, pull requests merged in 2020-04, with the labels that each got.

#825 the quick one that fixes colour problems with summary links
  components/vf-summary/vf-summary--profile.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Refactor

#828 Enhancement: notification cookie support
  components/embl-notifications/CHANGELOG.md
  components/embl-notifications/README.md
  components/embl-notifications/embl-notifications.js
Labels: Type: Enhancement

#829 Bug: avoid recursion in embl-conditional-edit
  components/embl-conditional-edit/CHANGELOG.md
  components/embl-conditional-edit/embl-conditional-edit.js
  components/vf-componenet-rollup/scripts.js
Labels: Type: Bug

#832 Bug: vf-form__core package missing component references
  components/vf-form/vf-form__core/CHANGELOG.md
  components/vf-form/vf-form__core/index.scss
  components/vf-form/vf-form__core/package.json
  components/vf-form/vf-form__core/yarn.lock
Labels: Priority: Medium, Type: Bug

#827 the one that adds some more banners
  components/vf-banner/README.md
  components/vf-banner/vf-banner--alerts.scss
  components/vf-banner/vf-banner--danger.njk
  components/vf-banner/vf-banner--info.njk
  components/vf-banner/vf-banner--success.njk
  components/vf-banner/vf-banner--warning.njk
  components/vf-banner/vf-banner.config.yml
  components/vf-banner/vf-banner.scss
  components/vf-button/vf-button.scss
  components/vf-componenet-rollup/index.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#835 the one where we look at link colours, again.
  components/vf-content/README.md
  components/vf-content/vf-content.config.yml
  components/vf-content/vf-content.scss
  components/vf-design-tokens/dist/sass/vf-links.variables.scss
  components/vf-design-tokens/src/core.palette.alias.yml
  components/vf-design-tokens/src/variables/vf-links.yml
  components/vf-link-list/vf-link-list.scss
  components/vf-link/vf-link--example.njk
  components/vf-link/vf-link--primary.scss
  components/vf-link/vf-link--secondary.scss
  components/vf-link/vf-link.config.yml
  components/vf-link/vf-link.scss
  components/vf-navigation/vf-navigation--global.scss
  components/vf-sass-config/mixins/_links.scss
  components/vf-summary/vf-summary--profile.scss
  components/vf-text/vf-text.njk
  components/vf-text/vf-text.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Refactor

#837 the one where there was a disco bug on the vf-tree's show/hide button
  components/vf-tree/CHANGELOG.md
  components/vf-tree/vf-tree.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#838 Bug: EMBL favicon and breadcrumbs
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup-example.njk
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.njk
  components/embl-conditional-edit/CHANGELOG.md
  components/embl-favicon/CHANGELOG.md
  components/embl-favicon/assets/site.webmanifest
  components/embl-favicon/embl-favicon.njk
  components/vf-favicon/CHANGELOG.md
  components/vf-favicon/assets/site.webmanifest
  components/vf-favicon/vf-favicon.config.yml
  components/vf-favicon/vf-favicon.njk
Labels: Priority: Medium, Type: Bug

#841 the one that fixes the style issues with buttons that were introduced with icon buttons
  components/vf-banner/vf-banner--alerts.scss
  components/vf-button/vf-button.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#842 The one that fixes text inputs on iOS
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__textarea/vf-form__textarea.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#836 the one that makes header components a little better
  components/vf-global-header/vf-global-header.scss
  components/vf-header/vf-header.config.yml
  components/vf-header/vf-header.scss
  components/vf-masthead/vf-masthead--supports.scss
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--main.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#844 the one that adds the max-width to images in components
  components/vf-figure/vf-figure.scss
  components/vf-link-list/vf-link-list.scss
  components/vf-video-teaser/vf-video-teaser.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#846 the one that makes the gdpr banner not merge with the footer
  components/vf-banner/vf-banner.scss
  components/vf-banner/vf-banner.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#847 the one that removes a parent class for the screen reader only class
  components/vf-utility-classes/vf-u-screen-reader.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#830 the one that adds tables to the component library
  components/vf-table/vf-table.config.yml
  components/vf-table/vf-table.njk
  components/vf-table/vf-table.scss
Labels: Status: WIP, Type: Component or Pattern, Type: Documentation

#843 The one where we make our CSS grid-gaps gaps
  components/embl-grid/embl-grid.scss
  components/vf-card-container/vf-card-container.scss
  components/vf-footer/vf-footer.scss
  components/vf-grid/vf-grid.scss
  components/vf-inlay/vf-inlay.scss
  components/vf-intro/vf-intro.scss
  components/vf-link-list/vf-link-list.scss
  components/vf-summary/vf-summary--has-image.scss
  components/vf-summary/vf-summary--news.scss
  components/vf-summary/vf-summary--profile.scss
  components/vf-summary/vf-summary.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#853 Chore: captilisation of "In this page"
  components/vf-article-meta-information/CHANGELOG.md
  components/vf-article-meta-information/vf-article-meta-information.config.yml
  components/vf-link-list/CHANGELOG.md
  components/vf-link-list/README.md
  components/vf-link-list/vf-link-list.config.yml
  components/vf-link-list/vf-link-list.njk
Labels: Priority: Low, Type: Chore

#845 the one that adds the vf-core ui colours as tokens
  components/vf-design-tokens/dist/json/vf-ui-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-ui-colors.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-ui-colors.map.scss
  components/vf-design-tokens/src/core.palette.alias.yml
  components/vf-design-tokens/vf-design-tokens--ui-colours.njk
  components/vf-design-tokens/vf-design-tokens.config.js
Labels: Priority: Low, Status: Review Needed, Type: Bug, Type: Enhancement

#855 the one that puts link list squares inside the box model
  components/vf-link-list/vf-link-list.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug, Type: Enhancement

#857 adds :focus styles to vf-button--outline
  components/vf-button/vf-button.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#858 the one that fixes the grey and lightest grey ui colour mixup
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.scss
  components/embl-grid/embl-grid.scss
  components/vf-box/vf-box--inlay.scss
  components/vf-box/vf-box.scss
  components/vf-card/vf-card.variables.scss
  components/vf-code-example/vf-code-example.scss
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-form/vf-form__fieldset/vf-form__fieldset.variables.scss
  components/vf-form/vf-form__input/vf-form__input.scss
  components/vf-form/vf-form__legend/vf-form__legend.variables.scss
  components/vf-form/vf-form__radio/vf-form__radio.scss
  components/vf-form/vf-form__select/vf-form__select.scss
  components/vf-form/vf-form__textarea/vf-form__textarea.scss
  components/vf-navigation/vf-navigation--main.scss
  components/vf-sass-config/mixins/_divider.scss
  components/vf-table/vf-table.scss
  tools/component-generator/templates/_component.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#859 Releases: vf-core 2.0.0
  package.json
Labels: Type: Chore

#860 the one that adds lots of more table things
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-table/CHANGELOG.md
  components/vf-table/README.md
  components/vf-table/vf-table.config.yml
  components/vf-table/vf-table.njk
  components/vf-table/vf-table.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#861 the one that fixes the hover colours in tables
  components/vf-table/CHANGELOG.md
  components/vf-table/vf-table.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#864 changes required astericks colour
  components/vf-form/vf-form__label/CHANGELOG.md
  components/vf-form/vf-form__label/vf-form__label.scss
Labels: Priority: Low, Status: Review Needed, Type: Component or Pattern

#863 the one that styles checkboxes inside of checkbox divs
  components/vf-form/vf-form__checkbox/CHANGELOG.md
  components/vf-form/vf-form__checkbox/vf-form__checkbox--inline.njk
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#866 the one that hopefully kickstarts Percy.io
  README.md
Labels: Priority: Low, Status: Review Needed, Type: Chore

#868 testing: test percy against develop
  .travis.yml
Labels: Type: Chore

#873 the one that makes section header links pass some #a11y rules
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.njk
Labels: Priority: Medium, Status: Review Needed, Type: Bug, Type: Component or Pattern

#879 BUG - Add underline to links in vf-banner
  components/embl-notifications/CHANGELOG.md
  components/embl-notifications/embl-notifications.js
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner--fixed.njk
  components/vf-banner/vf-banner--gdpr.scss
  components/vf-banner/vf-banner--phase.scss
  components/vf-banner/vf-banner--top.njk
  components/vf-banner/vf-banner.config.yml
  components/vf-banner/vf-banner.js
  components/vf-banner/vf-banner.scss
Labels: Priority: Medium, Type: Bug

#884 The one that adds more z-index to the system.
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-zindex.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-zindex.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-zindex.map.scss
  components/vf-design-tokens/src/maps/vf-zindex.yml
  components/vf-hero/vf-hero.scss
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation--main.scss
  components/vf-u-fullbleed/vf-u-fullbleed.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#882 the one where we get IE11 working better, again.
  components/vf-grid/CHANGELOG.md
  components/vf-grid/vf-grid.scss
Labels: Priority: High, Type: Bug, Type: Component or Pattern

#889 the one that adds some basic styling to tables for vf-content
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.njk
  components/vf-content/vf-content.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#890 the one where vf-figure floats
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.njk
  components/vf-content/vf-content.scss
  components/vf-figure/CHANGELOG.md
  components/vf-figure/vf-figure.config.yml
  components/vf-figure/vf-figure.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#888 the one that adds a simple social links component
  components/vf-componenet-rollup/index.scss
  components/vf-social-links/.npmignore
  components/vf-social-links/CHANGELOG.md
  components/vf-social-links/README.md
  components/vf-social-links/index.scss
  components/vf-social-links/package.json
  components/vf-social-links/vf-social-links.config.yml
  components/vf-social-links/vf-social-links.js
  components/vf-social-links/vf-social-links.njk
  components/vf-social-links/vf-social-links.scss
  components/vf-social-links/vf-social-links.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern

#893 the one where we create a better embedded content component
  components/vf-componenet-rollup/index.scss
  components/vf-embed/.npmignore
  components/vf-embed/CHANGELOG.md
  components/vf-embed/README.md
  components/vf-embed/index.scss
  components/vf-embed/package.json
  components/vf-embed/vf-embed.config.yml
  components/vf-embed/vf-embed.js
  components/vf-embed/vf-embed.njk
  components/vf-embed/vf-embed.scss
  components/vf-embed/vf-embed.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern

#892 the one that adds simple breakpoint documentation
  components/vf-design-tokens/dist/json/vf-breakpoints.ios.json
  components/vf-design-tokens/gulpfile.js
  components/vf-design-tokens/vf-design-tokens--breakpoints.njk
  components/vf-design-tokens/vf-design-tokens.config.js
Labels: Priority: Low, Status: Review Needed, Type: Documentation, Type: Enhancement
