Repository visual-framework/vf-core, pull requests merged in 2020-05, with the labels that each got.

#899 the one that updates the vf-embed component
  components/vf-embed/CHANGELOG.md
  components/vf-embed/README.md
  components/vf-embed/vf-embed.config.yml
  components/vf-embed/vf-embed.njk
  components/vf-embed/vf-embed.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#900 the one that finally removes calc from vf-grid fallback
  components/vf-grid/CHANGELOG.md
  components/vf-grid/vf-grid.scss
Labels: Priority: High, Type: Bug

#904 the one that changes the vf-figure component for the better
  components/vf-figure/CHANGELOG.md
  components/vf-figure/README.md
  components/vf-figure/vf-figure.config.yml
  components/vf-figure/vf-figure.njk
  components/vf-figure/vf-figure.scss
Labels: Priority: Medium, Status: Review Needed

#907 the one that adds a little theming for JS generated buttons in vf-banner
  components/vf-banner/CHANGELOG.md
  components/vf-banner/README.md
  components/vf-banner/vf-banner--top.njk
  components/vf-banner/vf-banner.js
Labels: Priority: Medium, Status: Review Needed

#894 the one that tidies up vf-masthead
  components/vf-card-container/vf-card-container.config.yml
  components/vf-header/vf-header--inlay.njk
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/README.md
  components/vf-masthead/assets/group-bg.jpg
  components/vf-masthead/assets/group-bg.png
  components/vf-masthead/vf-masthead--inlay.njk
  components/vf-masthead/vf-masthead--with-title-block.njk
  components/vf-masthead/vf-masthead.config.yml
  components/vf-masthead/vf-masthead.js
  components/vf-masthead/vf-masthead.njk
  components/vf-masthead/vf-masthead.scss
Labels: Priority: Medium, Status: WIP, Type: Component or Pattern, Type: Documentation, Type: Enhancement, Type: Refactor

#908 fixes vf-figure alignment inside vf-content
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.scss
Labels: Priority: Medium, Status: Review Needed

#912 the one where we had a spelling mistake
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead.js
  components/vf-masthead/vf-masthead.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#921 the one that makes a tiny change to vf-banner
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner--alerts.scss
  components/vf-banner/vf-banner--danger.njk
  components/vf-banner/vf-banner--info.njk
  components/vf-banner/vf-banner--success.njk
  components/vf-banner/vf-banner--warning.njk
  components/vf-banner/vf-banner.config.yml
  components/vf-banner/vf-banner.njk
Labels: Priority: Medium, Type: Breaking Change

#923 the one that makes the global header responsive-r
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.scss
Labels: Priority: High, Type: Bug

#924 the one that adds a wrap to the flex for smaller screens
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--main.scss
Labels: Priority: High, Type: Bug

#925 the one that normalises the banner vertical spacing
  components/vf-header/vf-header.scss
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead--supports.scss
  components/vf-masthead/vf-masthead.scss
Labels: Priority: Medium, Type: Refactor

#927 the one that adds a load of vf-grid utility classes
  components/vf-componenet-rollup/index.scss
  components/vf-design-tokens/dist/sass/maps/vf-breakpoints.map.scss
  components/vf-design-tokens/gulpfile.js
  components/vf-utility-classes/CHANGELOG.md
  components/vf-utility-classes/vf-u-grid.scss
  components/vf-utility-classes/vf-utility-classes--grid.njk
  components/vf-utility-classes/vf-utility-classes.scss
Labels: Priority: Medium, Type: Documentation, Type: Enhancement

#935 Enhancement: on ebi pages vf-divider shouldn't be capped at 80rem
  components/ebi-vf1-integration/CHANGELOG.md
  components/ebi-vf1-integration/ebi-vf1-integration.scss
Labels: Type: Enhancement

#929 the one where badges in a links_list with images works
  components/vf-banner/package.json
  components/vf-global-header/package.json
  components/vf-header/package.json
  components/vf-link-list/CHANGELOG.md
  components/vf-link-list/vf-link-list.scss
  components/vf-masthead/package.json
  components/vf-navigation/package.json
Labels: Status: Review Needed, Type: Enhancement

#943 the one that aligns arrows in trees
  components/vf-tree/CHANGELOG.md
  components/vf-tree/vf-tree.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#938 the one that removes horizontal padding from the global-header
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.scss
Labels: Status: Review Needed, Type: Refactor

#937 the one that removes padding and reduces margin from breadcrumbs
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-breadcrumbs/vf-breadcrumbs.variables.scss
Labels: Status: Review Needed, Type: Refactor

#944 the one that makes headings in vf-content stick to the correct font-weight
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#939 the one that centres content with less code
  components/vf-grid-page/CHANGELOG.md
  components/vf-grid-page/vf-grid-page.scss
Labels: Status: Review Needed, Type: Refactor

#941 the one that adds a border to a vf-footer with vf-u-fullbleed
  components/vf-footer/vf-footer.scss
  components/vf-u-fullbleed/CHANGELOG.md
Labels: Status: Review Needed, Type: Enhancement
