Repository visual-framework/vf-core, pull requests merged in 2020-07, with the labels that each got.

#1005 The one that doesn't squish the default avatar.
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--profile.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1006 Enhanchement: Backwards compatibility with vf-global-header 1.x HTML
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.scss
Labels: Priority: High, Type: Enhancement

#1008 the one that adds mailto: and tel: as appropriate
  components/vf-profile/CHANGELOG.md
  components/vf-profile/vf-profile.njk
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1007 the one that adds contextual data option to vf-hero
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.njk
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#1012 the one that refactors the vf-card and vf-card containers
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/vf-card-container.config.yml
  components/vf-card-container/vf-card-container.njk
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.njk
Labels: Priority: High, Status: Review Needed, Type: Refactor

#990 the one where we tentatively move to Dart Sass
  components/vf-componenet-rollup/index.scss
  package.json
  tools/gulp-tasks/vf-css.js
  yarn.lock
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#1017 the one that makes the profile a little more malleable.
  components/vf-profile/CHANGELOG.md
  components/vf-profile/vf-profile.scss
Labels: Priority: High, Status: Feedback Needed, Type: Bug

#1028 the one that refactors vf-links-list and vf-badge so it's more useful
  components/vf-badge/CHANGELOG.md
  components/vf-badge/README.md
  components/vf-badge/vf-badge.njk
  components/vf-link-list/CHANGELOG.md
  components/vf-link-list/index.scss
  components/vf-link-list/vf-link-list.config.yml
  components/vf-link-list/vf-link-list.njk
  components/vf-link-list/vf-link-list.scss
Labels: Priority: High, Status: Review Needed, Type: Enhancement, Type: Refactor

#1027 the one that updates vf-intro, to make it more useable in 11ty
  components/vf-intro/CHANGELOG.md
  components/vf-intro/README.md
  components/vf-intro/vf-intro.config.yml
  components/vf-intro/vf-intro.njk
Labels: Priority: High, Status: Review Needed, Type: Enhancement, Type: Refactor

#1029 the one fixes issue where SVG didn't appear in vf-links-list
  components/vf-link-list/CHANGELOG.md
  components/vf-link-list/vf-link-list.njk
Labels: Priority: High, Status: Review Needed, Type: Bug

#1030 the one that updates vf-intro a little better
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.njk
Labels: Priority: Medium, Status: Review Needed, Type: Bug, Type: Enhancement
