Repository visual-framework/vf-core, pull requests merged in 2020-03, with the labels that each got.

#785 the one where we update vf-links-list a little bit
  components/vf-intro/vf-intro.scss
  components/vf-link-list/README.md
  components/vf-link-list/vf-link-list.config.yml
  components/vf-link-list/vf-link-list.njk
  components/vf-link-list/vf-link-list.scss
Labels: Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#786 Component: embl-notifications
  components/embl-notifications/.npmignore
  components/embl-notifications/CHANGELOG.md
  components/embl-notifications/README.md
  components/embl-notifications/embl-notifications--example.njk
  components/embl-notifications/embl-notifications.config.yml
  components/embl-notifications/embl-notifications.js
  components/embl-notifications/embl-notifications.njk
  components/embl-notifications/embl-notifications.scss
  components/embl-notifications/embl-notifications.variables.scss
  components/embl-notifications/index.scss
  components/embl-notifications/package.json
  components/vf-banner/vf-banner.js
  components/vf-componenet-rollup/scripts.js
Labels: Status: WIP, Type: Component or Pattern

#793 bug: vf-figure path handling
  components/vf-figure/CHANGELOG.md
  components/vf-figure/vf-figure.config.yml
  components/vf-figure/vf-figure.njk
Labels: Type: Bug

#795 Bug: use embl.org over dev.beta.embl.org
  .gitlab-ci.yml
  components/ebi-vf1-integration/README.md
  components/embl-breadcrumbs-lookup/package.json
  components/embl-content-hub-loader/embl-content-hub-loader.njk
  components/embl-content-meta-properties/package.json
  components/embl-favicon/embl-favicon.njk
  components/embl-grid/package.json
  components/embl-logo/package.json
  components/vf-boilerplate-page/vf-boilerplate-page.njk
  components/vf-form/vf-form__checkbox/package.json
  components/vf-form/vf-form__helper/package.json
  components/vf-form/vf-form__input/package.json
  components/vf-form/vf-form__item/package.json
  components/vf-form/vf-form__label/package.json
  components/vf-form/vf-form__radio/package.json
  components/vf-form/vf-form__select/package.json
  components/vf-form/vf-form__textarea/package.json
Labels: Priority: High, Type: Bug

#787 Docs: update component template
  .github/ISSUE_TEMPLATE/new-component-request.md
  tools/component-generator/templates/_CHANGELOG.md
  tools/component-generator/templates/_README.md
  tools/component-generator/templates/_component.config.yml
  tools/component-generator/templates/_component.js
  tools/component-generator/templates/_component.njk
  tools/component-generator/templates/_component.scss
  tools/component-generator/templates/_component.variables.scss
  tools/component-generator/templates/_package.json
Labels: Priority: Medium, Type: Documentation

#797 Fix docs on embl-notifications
  components/embl-notifications/README.md
Labels: Type: Documentation

#794 chore: add-changelog-to-checklist
  .github/auto-comment.yml
Labels: Type: Chore

#799 Create vfGaIndicateLoaded
  components/vf-analytics-google/.npmignore
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/README.md
  components/vf-analytics-google/index.scss
  components/vf-analytics-google/package.json
  components/vf-analytics-google/vf-analytics-google.config.yml
  components/vf-analytics-google/vf-analytics-google.js
  components/vf-analytics-google/vf-analytics-google.njk
  components/vf-analytics-google/vf-analytics-google.scss
  components/vf-analytics-google/vf-analytics-google.variables.scss
  components/vf-componenet-rollup/scripts.js
Labels: Type: Component or Pattern

#796 the one that adds a full bleed utility class
  components/vf-componenet-rollup/index.scss
  components/vf-u-fullbleed/.npmignore
  components/vf-u-fullbleed/CHANGELOG.md
  components/vf-u-fullbleed/README.md
  components/vf-u-fullbleed/index.scss
  components/vf-u-fullbleed/package.json
  components/vf-u-fullbleed/vf-u-fullbleed.config.yml
  components/vf-u-fullbleed/vf-u-fullbleed.js
  components/vf-u-fullbleed/vf-u-fullbleed.njk
  components/vf-u-fullbleed/vf-u-fullbleed.scss
  components/vf-u-fullbleed/vf-u-fullbleed.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern

#798 bug: favicon paths
  components/vf-favicon/CHANGELOG.md
  components/vf-favicon/README.md
  components/vf-favicon/vf-favicon.config.yml
Labels: Type: Bug

#800 adds a variable for defining where the parent CSS is placed
  components/vf-u-fullbleed/README.md
  components/vf-u-fullbleed/vf-u-fullbleed.scss
Labels: Priority: Low, Type: Documentation, Type: Enhancement

#803 EMBL Notifications could sometimes not insert correctly
  components/embl-content-hub-loader/README.md
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  components/embl-notifications/README.md
  components/embl-notifications/embl-notifications--example.njk
  components/embl-notifications/embl-notifications.js
  components/vf-componenet-rollup/scripts.js
Labels: Priority: Medium, Type: Bug

#802 fixes issue with vf-grid in production
  components/vf-grid/README.md
  components/vf-grid/vf-grid.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#805 makes changes so njk works in 11ty or WP
  components/vf-box/vf-box.njk
  components/vf-card/vf-card.njk
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Enhancement

#807 adds simple CSS for inline links in vf-box__text
  components/vf-box/README.md
  components/vf-box/vf-box.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#814 Fix vf-content blockquote spacing
  .github/auto-comment.yml
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.njk
  components/vf-content/vf-content.scss
Labels: Type: Bug

#815 adds bottom margin to video in vf-content
  components/vf-content/vf-content.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#822 The one that updates article meta information
  components/vf-article-meta-information/vf-article-meta-information.config.yml
  components/vf-article-meta-information/vf-article-meta-information.njk
  components/vf-article-meta-information/vf-article-meta-information.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#817 Enhancement: build out notication banners
  components/embl-notifications/CHANGELOG.md
  components/embl-notifications/embl-notifications.js
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner--fixed.njk
  components/vf-banner/vf-banner--gdpr.scss
  components/vf-banner/vf-banner--inline.njk
  components/vf-banner/vf-banner--phase.scss
  components/vf-banner/vf-banner--top.njk
  components/vf-banner/vf-banner.scss
Labels: Priority: Medium, Type: Enhancement
