Repository visual-framework/vf-core, pull requests merged in 2020-08, with the labels that each got.

#1033 the one that finally deprecates the vf-summary--profile variant
  components/vf-summary/CHANGELOG.md
  components/vf-summary/README.md
  components/vf-summary/vf-summary--profile.scss
  components/vf-summary/vf-summary.config.yml
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1034 The one that fixes up issues with vf-intro
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.config.yml
  components/vf-intro/vf-intro.njk
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Enhancement, Type: Refactor

#1037 Clean up redundant dependencies
  package.json
  yarn.lock
Labels: Type: Chore, Type: Enhancement

#1046 The one that makes the link icon for section headers alway be top/right of the content
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1044 chore: better split out build dependencies
  tools/vf-core/package.json
  tools/vf-sass-compilation/README.md
  tools/vf-sass-compilation/package.json
  yarn.lock
Labels: Type: Chore

#1049 the one that updates vf-button so it works again
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.njk
Labels: Priority: High, Status: Review Needed, Type: Bug

#1050 adds some utility classes for various bits of vf-grid
  components/vf-grid/vf-grid.scss
  components/vf-sass-config/mixins/_utility--grid-gap.scss
  components/vf-sass-config/mixins/_vf-utility-mixins.scss
  components/vf-utility-classes/vf-utility-classes--grid-gap.njk
  components/vf-utility-classes/vf-utility-classes.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#1053 The one that makes your computer fan a little quieter
  tools/vf-core/CHANGELOG.md
  tools/vf-core/gulp-tasks/vf-watch.js
Labels: Priority: Low, Status: Review Needed, Type: Bug, Type: Chore, Type: Enhancement

#1054 Update deploy-aws
  bin/deploy-aws
Labels: Type: Chore

#1055 Update giltab deploy path
  .gitlab-ci.yml
Labels: Type: Chore

#1056 🔧 the one that adds an if statement example for setting context
  tools/vf-component-generator/templates/_CHANGELOG.md
  tools/vf-component-generator/templates/_component.njk
Labels: Priority: Low, Status: Review Needed, Type: Chore

#1058 💬 tidies up the changelog.md template
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/templates/_CHANGELOG.md
Labels: Status: Review Needed, Type: Refactor

#1061 fix: vf-component-generator
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/README.md
  tools/vf-component-generator/gulp-tasks/vf-generator.js
  tools/vf-component-generator/gulpfile.js
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/developing/components/creating-new-components.njk
  tools/vf-core/CHANGELOG.md
  tools/vf-core/README.md
  tools/vf-core/gulp-tasks/_gulp_rollup.js
  yarn.lock
Labels: Type: Bug, Type: Chore

#1062 Component: vf-details
  components/vf-componenet-rollup/index.scss
  components/vf-details/.npmignore
  components/vf-details/CHANGELOG.md
  components/vf-details/README.md
  components/vf-details/index.scss
  components/vf-details/package.json
  components/vf-details/vf-details.config.yml
  components/vf-details/vf-details.js
  components/vf-details/vf-details.njk
  components/vf-details/vf-details.scss
  components/vf-details/vf-details.variables.scss
Labels: Type: Component or Pattern

#1064 Fix: generate per-component CSS with `vf-css:generate-component-css`
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/gulpfile.js
Labels: Type: Chore

#1063 🎨 the one that replaces vf-grid-page with vf-body
  components/_previews/_preview--nogrid.njk
  components/vf-body/.npmignore
  components/vf-body/CHANGELOG.md
  components/vf-body/README.md
  components/vf-body/index.scss
  components/vf-body/package.json
  components/vf-body/vf-body.config.yml
  components/vf-body/vf-body.njk
  components/vf-body/vf-body.scss
  components/vf-componenet-rollup/index.scss
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/sass/vf-layout.variables.scss
  components/vf-design-tokens/src/variables/vf-layout.yml
  components/vf-grid-page/CHANGELOG.md
  components/vf-grid-page/README.md
  components/vf-grid-page/vf-grid-page.config.yml
  components/vf-grid-page/vf-grid-page.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/index.scss
  components/vf-sass-config/variables/vf-global-custom-properties.scss
  components/vf-sass-config/variables/vf-variables.scss
Labels: Priority: High, Status: Review Needed, Type: Refactor

#1065 Component: vf-show-more
  components/ebi-header-footer/ebi-header-footer.js
  components/vf-componenet-rollup/index.scss
  components/vf-componenet-rollup/scripts.js
  components/vf-show-more/.npmignore
  components/vf-show-more/CHANGELOG.md
  components/vf-show-more/README.md
  components/vf-show-more/index.scss
  components/vf-show-more/package.json
  components/vf-show-more/vf-show-more.config.yml
  components/vf-show-more/vf-show-more.js
  components/vf-show-more/vf-show-more.njk
  components/vf-show-more/vf-show-more.scss
  components/vf-show-more/vf-show-more.variables.scss
Labels: Type: Component or Pattern

#1068 Add a 404 with search to component library
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/gulpfile.js
  tools/vf-component-library/src/site/404.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
Labels: Type: Chore, Type: Enhancement

#1066 Compoennt/vf google analytics improvements
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Priority: Medium, Type: Component or Pattern, Type: Enhancement

#1070 🚑 the one that updates max-width to use a Sass variable as needed
  components/ebi-vf1-integration/CHANGELOG.md
  components/ebi-vf1-integration/ebi-vf1-integration.scss
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.scss
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner--fixed.scss
  components/vf-banner/vf-banner.scss
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/vf-card-container.scss
  components/vf-footer/CHANGELOG.md
  components/vf-footer/vf-footer.scss
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
  components/vf-inlay/CHANGELOG.md
  components/vf-inlay/vf-inlay.scss
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--main.scss
Labels: Status: Review Needed, Type: Bug

#1071 chore: fixup-vf-component-library
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/gulpfile.js
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic.njk
Labels: Priority: Low, Type: Bug, Type: Chore

#1018 the one that tidies up the `vf-inlay` layout as it moves towards deprecation.
  components/embl-grid/embl-grid.scss
  components/vf-inlay/CHANGELOG.md
  components/vf-inlay/vf-inlay.njk
  components/vf-inlay/vf-inlay.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1072 🎨 the one that refactors the `embl-grid` code and gives columns a little more space
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.njk
  components/embl-grid/embl-grid.scss
  components/vf-sass-config/variables/vf-global-custom-properties.scss
Labels: Status: Review Needed, Type: Enhancement, Type: Refactor

#1039 Refactor/primary secondary tertiary colours
  components/vf-badge/CHANGELOG.md
  components/vf-badge/vf-badge.config.yml
  components/vf-badge/vf-badge.scss
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.scss
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.scss
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-themes.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-themes.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-themes.map.scss
  components/vf-design-tokens/src/maps/vf-themes.yml
  components/vf-design-tokens/vf-design-tokens--themes.njk
  components/vf-design-tokens/vf-design-tokens.config.js
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead.scss
  components/vf-profile/CHANGELOG.md
  components/vf-profile/vf-profile.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/functions/_theme.scss
  components/vf-sass-config/functions/vf-functions.scss
  components/vf-sass-config/mixins/_theme.scss
  components/vf-sass-config/mixins/_vf-mixins.scss
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--event.scss
Labels: Priority: Medium, Status: WIP, Type: Enhancement, Type: Refactor

#1073 bug: css nano aggressive grid optimizations
  tools/vf-core/CHANGELOG.md
  tools/vf-core/gulp-tasks/vf-css.js
Labels: Priority: Critical, Type: Bug
