Repository visual-framework/vf-core, pull requests merged in 2020-01, with the labels that each got.

#697 ENHANCEMENT - Component release workflow
  PUBLISHING.md
  package.json
Labels: Priority: Low, Type: Enhancement

#702 FEATURE: Create github workflow
  .github/workflows/nodejs.yml
Labels: Type: Feature

#704 CHORE: update-publishing-notes
  PUBLISHING.md
Labels: Type: Chore, Type: Documentation

#706 enhancment: use prepublishOnly
  package.json
Labels: Priority: Low, Type: Enhancement

#711 the one where jobs get a blue button
  components/vf-blockquote/vf-blockquote.scss
  components/vf-summary/vf-summary--job.njk
Labels: Status: Review Needed, Type: Component or Pattern, Type: Refactor

#717 Enable scheduling for renovate
  .github/auto-comment.yml
  renovate.json
Labels: Priority: Low, Type: Chore, Type: Enhancement

#722 Add vf-u-text--break
  components/vf-utility-classes/CHANGELOG.md
  components/vf-utility-classes/vf-u-text.scss
  components/vf-utility-classes/vf-utility-classes.njk
Labels: Priority: Low, Type: Enhancement

#725 Component: vf polyfill js
  .vscode/settings.json
  components/vf-polyfill-js/.npmignore
  components/vf-polyfill-js/CHANGELOG.md
  components/vf-polyfill-js/README.md
  components/vf-polyfill-js/index.scss
  components/vf-polyfill-js/package.json
  components/vf-polyfill-js/vf-polyfill-js.config.yml
  components/vf-polyfill-js/vf-polyfill-js.js
  components/vf-polyfill-js/vf-polyfill-js.njk
  components/vf-polyfill-js/vf-polyfill-js.scss
  components/vf-polyfill-js/vf-polyfill-js.variables.scss
  tools/vf-frctl-theme/views/layouts/skeleton.njk
Labels: Priority: Medium, Type: Component or Pattern

#723 Bug - babel js presets
  package.json
  tools/gulp-tasks/vf-scripts.js
Labels: Priority: Critical, Type: Bug

#733 the one where we re-introduce a responsive logo
  components/embl-logo/embl-logo.config.yml
  components/embl-logo/embl-logo.njk
  components/embl-logo/embl-logo.scss
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.scss
Labels: Priority: High, Type: Enhancement

#735 the one where we update the section header again
  components/vf-section-header/vf-section-header.config.yml
  components/vf-section-header/vf-section-header.njk
  components/vf-section-header/vf-section-header.scss
Labels: Priority: Low, Type: Enhancement

#709 the one where we refactor the card component
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
Labels: Status: WIP, Type: Breaking Change, Type: Component or Pattern, Type: Refactor

#736 Documentation: note yaml component syntax
  .vscode/spellright.dict
  tools/component-generator/templates/_component.config.yml
  tools/component-generator/templates/_component.js
  tools/vf-config/CHANGELOG.md
Labels: Priority: Low, Type: Chore, Type: Documentation

#741 Bug/vf-clean
  tools/gulp-tasks/_gulp_rollup.js
  tools/gulp-tasks/vf-cleanup.js
Labels: Priority: Medium, Type: Bug

#738 Bug/component hotfixes
  components/vf-card-container/vf-card-container.config.yml
  components/vf-card-container/vf-card-container.njk
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
  components/vf-section-header/vf-section-header.njk
  components/vf-section-header/vf-section-header.scss
Labels: Priority: High, Type: Bug
