Repository visual-framework/vf-core, pull requests merged in 2020-10, with the labels that each got.

#1141 Issue-1140 : Refactor console verbose logging for GA events
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Status: Review Needed, Type: Refactor

#1134 bug: design tokens demo not shown
  components/vf-analytics-google/CHANGELOG.md
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/vf-design-tokens.config.js
Labels: Priority: High, Type: Bug

#1147 enhancement: add support for the autofocus attribute
  components/vf-search-client-side/CHANGELOG.md
  components/vf-search-client-side/README.md
  components/vf-search-client-side/vf-search-client-side.config.yml
  components/vf-search-client-side/vf-search-client-side.njk
  components/vf-search/CHANGELOG.md
  components/vf-search/README.md
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
Labels: Type: Enhancement

#1144 Docs: cleanup and boilerplates
  tools/vf-component-library/src/site/404.njk
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/about/faq.njk
  tools/vf-component-library/src/site/about/index.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/demos/index.njk
  tools/vf-component-library/src/site/demos/integration-bootstrap.njk
  tools/vf-component-library/src/site/demos/integration-vf1.njk
  tools/vf-component-library/src/site/developing/index.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/templates/notice-boilerplate.njk
  tools/vf-component-library/src/site/search.njk
  tools/vf-component-library/src/site/troubleshooting/index.njk
  tools/vf-component-library/src/site/updates.njk
Labels: Type: Documentation

#1154 Docs: onboarding typos and fixes
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/index.njk
Labels: Type: Documentation

#1155 the one that takes the hero component back to 1999
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1157 Enhancement: analytics, add support for not tracking the initial page view
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/README.md
  components/vf-analytics-google/vf-analytics-google.js
  components/vf-componenet-rollup/scripts.js
Labels: Type: Enhancement

#1158 chore: vf-banner-log-cleanup
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.js
Labels: Priority: Low, Type: Chore

#1159 bug: vf-hero css typo
  components/vf-hero/vf-hero.scss
Labels: Type: Bug

#1125 💄 the one that makes `vf-divider` a little more malleable.
  components/_previews/_preview--body.njk
  components/vf-divider/CHANGELOG.md
  components/vf-divider/README.md
  components/vf-divider/vf-divider.config.yml
  components/vf-divider/vf-divider.njk
  components/vf-divider/vf-divider.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/mixins/_divider.scss
  components/vf-u-fullbleed/CHANGELOG.md
  components/vf-u-fullbleed/vf-u-fullbleed.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1156 the one that lets us have more space, what a concept.
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.variables.scss
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.variables.scss
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.scss
  components/vf-code-example/CHANGELOG.md
  components/vf-code-example/vf-code-example.scss
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.scss
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-spacing.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-spacing.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-spacing.map.scss
  components/vf-design-tokens/src/maps/vf-spacing.yml
  components/vf-details/CHANGELOG.md
  components/vf-details/vf-details.scss
  components/vf-form/vf-form__fieldset/CHANGELOG.md
  components/vf-form/vf-form__fieldset/vf-form__fieldset.scss
  components/vf-form/vf-form__label/CHANGELOG.md
  components/vf-form/vf-form__label/vf-form__label.scss
  components/vf-form/vf-form__legend/CHANGELOG.md
  components/vf-form/vf-form__legend/vf-form__legend.scss
  components/vf-link-list/CHANGELOG.md
  components/vf-link-list/vf-link-list.scss
  components/vf-logo/CHANGELOG.md
  components/vf-logo/vf-logo.scss
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead--supports.scss
  components/vf-page-header/CHANGELOG.md
  components/vf-page-header/vf-page-header.scss
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/README.md
  components/vf-sass-config/mixins/_lists.scss
  components/vf-sass-config/mixins/_margin.scss
  components/vf-sass-config/mixins/_padding.scss
  components/vf-sass-config/mixins/_typography.scss
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.scss
  components/vf-utility-classes/CHANGELOG.md
  components/vf-utility-classes/vf-utility-classes--grid-gap.njk
  components/vf-utility-classes/vf-utility-classes.njk
Labels: Priority: High, Status: Review Needed, Type: Refactor

#1160 Fix: Wallace failing CI builds
  .travis.yml
Labels: Type: Bug

#1162 feature: vf-ga network support
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/README.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Type: Enhancement

#1166 Enhancement: echo component generation time
  components/vf-componenet-rollup/CHANGELOG.md
  components/vf-componenet-rollup/index.scss
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/templates/_component.scss
  tools/vf-core/CHANGELOG.md
  tools/vf-core/gulp-tasks/vf-css.js
Labels: Type: Enhancement

#1169 Chore: Update utility spacing in component library
  tools/vf-component-library/src/site/_includes/layouts/components.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/scientific-service.njk
  tools/vf-component-library/src/site/updates.njk
  tools/vf-frctl-theme/views/macros/navigation.njk
  tools/vf-frctl-theme/views/partials/browser/browser.njk
  tools/vf-frctl-theme/views/partials/browser/panel-notes.njk
  tools/vf-frctl-theme/views/partials/pen/preview.njk
Labels: Type: Chore

#1170 Fix: fractal bootstrap
  tools/vf-component-initialization/CHANGELOG.md
  tools/vf-component-initialization/package.json
Labels: Priority: High, Type: Bug

#1172 📝 the one that updates the design tokens documentation pages
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/README.md
  components/vf-design-tokens/vf-design-tokens--breakpoints.njk
  components/vf-design-tokens/vf-design-tokens--colours.njk
  components/vf-design-tokens/vf-design-tokens--spacing.njk
  components/vf-design-tokens/vf-design-tokens--themes.njk
  components/vf-design-tokens/vf-design-tokens--typography.njk
  components/vf-design-tokens/vf-design-tokens--ui-colours.njk
  components/vf-design-tokens/vf-design-tokens.config.js
Labels: Priority: Medium, Status: Review Needed, Type: Documentation, Type: Refactor

#1174 the one that refactors vf-intro
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.config.yml
  components/vf-intro/vf-intro.njk
  components/vf-intro/vf-intro.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1171 Create 2.3.0 release notes
  PUBLISHING.md
  package.json
  tools/vf-component-library/src/site/patterns/index.njk
  tools/vf-component-library/src/site/updates/2020-10-20-a-better-space.njk
  tools/vf-component-library/src/site/updates/2020-10-20-component-updates.md
Labels: Type: Documentation

#1173 adds some simple, easier to find design tokens pages
  tools/vf-component-library/package-lock.json
  tools/vf-component-library/src/site/_data/blocks.json
  tools/vf-component-library/src/site/_data/containers.json
  tools/vf-component-library/src/site/_data/elements.json
  tools/vf-component-library/src/site/_data/utilities.json
  tools/vf-component-library/src/site/_includes/layouts/tokens.njk
  tools/vf-component-library/src/site/design-tokens/breakpoints.njk
  tools/vf-component-library/src/site/design-tokens/colours.njk
  tools/vf-component-library/src/site/design-tokens/index.njk
  tools/vf-component-library/src/site/design-tokens/spacing.njk
  tools/vf-component-library/src/site/design-tokens/theming.njk
  tools/vf-component-library/src/site/design-tokens/typography.njk
Labels: Priority: Low, Status: Review Needed, Type: Documentation

#1179 📝 The one that updates the design tokens docs.
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/README.md
  components/vf-design-tokens/vf-design-tokens--breakpoints.njk
  components/vf-design-tokens/vf-design-tokens--colours.njk
  components/vf-design-tokens/vf-design-tokens--spacing.njk
  components/vf-design-tokens/vf-design-tokens--themes.njk
  components/vf-design-tokens/vf-design-tokens--typography.njk
  components/vf-design-tokens/vf-design-tokens--ui-colours.njk
  components/vf-design-tokens/vf-design-tokens.config.js
  components/vf-design-tokens/vf-design-tokens.njk
  components/vf-design-tokens/vf-design-tokens.scss
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/gulp-tasks/tokens.js
  tools/vf-component-library/gulpfile.js
  tools/vf-component-library/package-lock.json
  tools/vf-component-library/package.json
  tools/vf-component-library/src/site/design-tokens/breakpoints.njk
  tools/vf-component-library/src/site/design-tokens/colours.njk
  tools/vf-component-library/src/site/design-tokens/design-tokens.11tydata.json
  tools/vf-component-library/src/site/design-tokens/index.njk
  tools/vf-component-library/src/site/design-tokens/spacing.njk
  tools/vf-component-library/src/site/design-tokens/theming.njk
  tools/vf-component-library/src/site/design-tokens/typography.njk
Labels: Priority: Medium, Status: Review Needed, Type: Documentation, Type: Enhancement

#1178 fix: linting defaults
  tools/vf-core/CHANGELOG.md
  tools/vf-core/gulp-tasks/vf-scripts.js
Labels: Type: Bug

#1180 the one that tidies up some of the space
  components/embl-logo/CHANGELOG.md
  components/embl-logo/embl-logo.scss
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-breadcrumbs/vf-breadcrumbs.scss
  components/vf-breadcrumbs/vf-breadcrumbs.variables.scss
  components/vf-global-header/CHANGELOG.md
  components/vf-global-header/vf-global-header.scss
  components/vf-header/CHANGELOG.md
  components/vf-header/vf-header.scss
Labels: Type: Enhancement, Type: Refactor

#1186 the one that makes 11ty look for design tokens data
  tools/vf-component-library/gulp-tasks/tokens.js
  tools/vf-component-library/gulpfile.js
  tools/vf-component-library/package.json
  tools/vf-component-library/src/site/_data/tokens/breakpoints.js
  tools/vf-component-library/src/site/_data/tokens/colours.js
  tools/vf-component-library/src/site/_data/tokens/spacing.js
  tools/vf-component-library/src/site/_data/tokens/theming.js
  tools/vf-component-library/src/site/_data/tokens/typographyMono.js
  tools/vf-component-library/src/site/_data/tokens/typographySans.js
  tools/vf-component-library/src/site/_data/tokens/uiColors.js
  tools/vf-component-library/src/site/design-tokens/breakpoints.njk
  tools/vf-component-library/src/site/design-tokens/colours.njk
  tools/vf-component-library/src/site/design-tokens/design-tokens.11tydata.json
  tools/vf-component-library/src/site/design-tokens/spacing.njk
  tools/vf-component-library/src/site/design-tokens/theming.njk
  tools/vf-component-library/src/site/design-tokens/typography.njk
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1181 the one that tidies up components and makes their spacing numerical
  components/vf-box/CHANGELOG.md
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.njk
  components/vf-box/vf-box.scss
  components/vf-cluster/CHANGELOG.md
  components/vf-cluster/vf-cluster--400.njk
  components/vf-cluster/vf-cluster--600.njk
  components/vf-cluster/vf-cluster--800.njk
  components/vf-cluster/vf-cluster.config.yml
  components/vf-cluster/vf-cluster.scss
  components/vf-stack/CHANGELOG.md
  components/vf-stack/vf-stack--400.njk
  components/vf-stack/vf-stack--600.njk
  components/vf-stack/vf-stack--800.njk
  components/vf-stack/vf-stack.config.yml
  components/vf-stack/vf-stack.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1187 the one that adds gap spacing back to the vf-intro grid
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#1192 chore: reclassify component types
  components/ebi-header-footer/ebi-header-footer.config.yml
  components/embl-conditional-edit/embl-conditional-edit.config.yml
  components/embl-content-hub-loader/embl-content-hub-loader.config.yml
  components/embl-content-meta-properties/embl-content-meta-properties.config.yml
  components/vf-details/vf-details.config.yml
  components/vf-search-client-side/vf-search-client-side.config.yml
  components/vf-show-more/vf-show-more.config.yml
Labels: Type: Chore, Type: Documentation

#1193 chore: js linting fixes
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-conditional-edit/embl-conditional-edit.js
  components/embl-content-hub-loader/embl-content-hub-loader.js
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
  components/embl-content-hub-loader/embl-content-hub-loader__html-imports.js
  components/embl-content-meta-properties/embl-content-meta-properties.js
  components/embl-notifications/embl-notifications.js
  components/vf-banner/vf-banner.js
  components/vf-componenet-rollup/scripts.js
  components/vf-design-tokens/gulpfile.js
  components/vf-design-tokens/vf-design-tokens.config.js
  components/vf-discussion/vf-discussion.js
  components/vf-form/vf-form__core/assets/vf-form__float-labels.js
  components/vf-hero/assets/jarallax.js
  components/vf-lede/vf-lede.js
  components/vf-location-nearest/vf-location-nearest.js
  components/vf-masthead/vf-masthead.js
  components/vf-pagination/vf-pagination.js
  components/vf-search-client-side/vf-search-client-side.js
  components/vf-search/vf-search.js
  components/vf-show-more/vf-show-more.js
  components/vf-tabs/vf-tabs.js
  components/vf-tree/vf-tree.js
Labels: Type: Chore

#1188 the one that renames and moves all grid components as layout components
  components/embl-grid/embl-grid.config.yml
  components/vf-body/vf-body.config.yml
  components/vf-cluster/vf-cluster.config.yml
  components/vf-grid/vf-grid.config.yml
  components/vf-inlay/vf-inlay.config.yml
  components/vf-stack/vf-stack.config.yml
  tools/vf-component-generator/index.js
  tools/vf-component-library/src/site/_includes/layouts/components.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-frctl-theme/views/partials/browser/component-list.njk
Labels: Priority: Medium, Status: Review Needed, Type: Documentation

#1194 the one that removes card and adds inline checkerboard background for component views
  tools/vf-component-library/src/site/_includes/layouts/components.njk
Labels: Priority: Medium, Status: Review Needed, Type: Documentation, Type: Enhancement

#1199 Chore: update gitlab to deploy to new domain
  .gitlab-ci.yml
Labels: Type: Chore

#1195 the one that refactors the masthead
  .gitignore
  components/vf-componenet-rollup/index.scss
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/README.md
  components/vf-masthead/vf-masthead--supports.scss
  components/vf-masthead/vf-masthead.config.yml
  components/vf-masthead/vf-masthead.js
  components/vf-masthead/vf-masthead.njk
  components/vf-masthead/vf-masthead.scss
Labels: Priority: Medium, Status: Feedback Needed, Status: WIP, Type: Enhancement, Type: Refactor

#1203 the one that fixes a bug introduced to `vf-navigation--additional`
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--additional.scss
  components/vf-navigation/vf-navigation.config.yml
  components/vf-navigation/vf-navigation.njk
Labels: Priority: High, Status: Review Needed, Type: Bug

#1204 The one that deprecates the vf-inlay pattern.
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.scss
  components/vf-componenet-rollup/index.scss
  components/vf-header/CHANGELOG.md
  components/vf-header/vf-header--inlay.njk
  components/vf-header/vf-header.scss
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
  components/vf-inlay/CHANGELOG.md
  components/vf-inlay/vf-inlay.config.yml
  components/vf-inlay/vf-inlay.scss
Labels: Priority: Low, Status: Review Needed, Type: Breaking Change, Type: Refactor

#1206 the one that updates grid gap sizing and column size
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-global-custom-properties.scss
Labels: Priority: Low, Status: Review Needed, Type: Changelog, Type: Enhancement

#1207 the one that brings small improvements to breadcrumbs
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-breadcrumbs/vf-breadcrumbs--with-related.njk
  components/vf-breadcrumbs/vf-breadcrumbs.config.yml
  components/vf-breadcrumbs/vf-breadcrumbs.njk
  components/vf-breadcrumbs/vf-breadcrumbs.scss
Labels: Priority: Low, Status: Review Needed, Type: Breaking Change, Type: Enhancement
