Repository visual-framework/vf-core, pull requests merged in 2020-02, with the labels that each got.

#750 Make the right sidebar of vf-inlay responsive
  components/vf-inlay/vf-inlay.scss
Labels: Type: Feature

#752 Bug/embl logo no width
  components/embl-logo/embl-logo.scss
  components/vf-inlay/vf-inlay.scss
Labels: Priority: Medium, Type: Bug

#760 Chore/backport fixes
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.scss
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.scss
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.scss
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/vf-card-container.scss
  components/vf-footer/CHANGELOG.md
  components/vf-footer/vf-footer.njk
  components/vf-footer/vf-footer.scss
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.scss
Labels: Priority: Medium, Type: Chore

#765 The one where the vf-box component gets a makeover
  components/vf-badge/vf-badge.config.yml
  components/vf-box/CHANGELOG.md
  components/vf-box/README.md
  components/vf-box/vf-box--factoid.scss
  components/vf-box/vf-box--inlay.scss
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.njk
  components/vf-box/vf-box.scss
  components/vf-button/vf-button.config.yml
  components/vf-card-container/vf-card-container.config.yml
  components/vf-card/vf-card.config.yml
  components/vf-link/vf-link.config.yml
Labels: Priority: High, Status: Review Needed, Type: Enhancement, Type: Refactor

#766 the one with the updates to make vf-box better and docs clearer
  components/vf-box/README.md
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#767 Suggestion: Hide is-a-link and use in some examples
  components/vf-box/vf-box.config.yml
Labels: Type: Enhancement

#769 the one where we update the mortal kombat levels of design
  components/vf-box/CHANGELOG.md
  components/vf-box/README.md
  components/vf-box/vf-box.config.yml
  components/vf-box/vf-box.scss
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.scss
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero--example.njk
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--main.scss
  components/vf-navigation/vf-navigation.config.yml
Labels: Priority: High, Status: Review Needed, Type: Breaking Change, Type: Enhancement, Type: Refactor

#770 bug: vf-form js robustness
  components/vf-form/vf-form__core/assets/vf-form__float-labels.js
Labels: Priority: High, Type: Bug

#771 Enhancement: embl breadcrumb robustness
  components/embl-breadcrumbs-lookup/CHANGELOG.md
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
Labels: Type: Enhancement

#772 enhancement: embl-breadcrumb-lookup
  components/embl-breadcrumbs-lookup/CHANGELOG.md
  components/embl-breadcrumbs-lookup/README.md
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.njk
Labels: Type: Enhancement

#774 Enhancement: embl-content-hub-loader handle no results
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/README.md
  components/embl-content-hub-loader/embl-content-hub-loader__fetch.js
Labels: Type: Enhancement

#777 The one where the vf-section-header goes all blue
  components/vf-sass-config/CHANGELOG.md
  components/vf-section-header/vf-section-header.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug, Type: Refactor

#776 Breadcrumbs: improve edge case handling
  components/embl-breadcrumbs-lookup/CHANGELOG.md
  components/embl-breadcrumbs-lookup/README.md
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.njk
Labels: Type: Enhancement

#778 chore: update-vf-section-header-changelog
  components/vf-sass-config/CHANGELOG.md
  components/vf-section-header/CHANGELOG.md
Labels: Type: Chore

#780 Component/vf summary event
  components/vf-componenet-rollup/index.scss
  components/vf-summary/vf-summary--event-easy.njk
  components/vf-summary/vf-summary--event.njk
  components/vf-summary/vf-summary--event.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Enhancement

#781 Clean up ebi-header-footer
  components/ebi-header-footer/ebi-header-footer--embl-selector.scss
  components/ebi-header-footer/ebi-header-footer--footer.scss
  components/ebi-header-footer/ebi-header-footer--form.scss
  components/ebi-header-footer/ebi-header-footer--header.scss
  components/ebi-header-footer/ebi-header-footer--layout.scss
  components/ebi-header-footer/ebi-header-footer.njk
  components/ebi-header-footer/ebi-header-footer.scss
Labels: Type: Enhancement
