Repository visual-framework/vf-core, pull requests merged in 2021-03, with the labels that each got.

#1405 The one that fixes any stylelint errors
  .stylelintrc
  components/embl-grid/CHANGELOG.md
  components/embl-grid/embl-grid.scss
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
  components/vf-embed/CHANGELOG.md
  components/vf-embed/vf-embed.scss
  components/vf-form/vf-form__checkbox/CHANGELOG.md
  components/vf-form/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-form/vf-form__radio/CHANGELOG.md
  components/vf-form/vf-form__radio/vf-form__radio.scss
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.scss
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead.scss
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/vf-navigation--main.scss
  components/vf-news-container/CHANGELOG.md
  components/vf-news-container/vf-news-container.scss
  components/vf-pagination/CHANGELOG.md
  components/vf-pagination/vf-pagination.scss
  components/vf-search-client-side/CHANGELOG.md
  components/vf-search-client-side/vf-search-client-side.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1407 Docs: governance and consultation
  tools/vf-component-library/src/site/about/consultation.njk
Labels: Type: Documentation

#1394 The one that makes us practice what we preach with buttons
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/src/site/index.njk
Labels: Priority: Low, Status: Review Needed, Type: Documentation

#1411 the one that makes the inline search variant better when it has less space
  components/vf-search/CHANGELOG.md
  components/vf-search/README.md
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
  components/vf-search/vf-search.scss
Labels: Priority: High, Status: Review Needed, Type: Breaking Change, Type: Enhancement

#1420 the one that adds more vf-stacks
  components/vf-stack/CHANGELOG.md
  components/vf-stack/vf-stack--1200.njk
  components/vf-stack/vf-stack--1600.njk
  components/vf-stack/vf-stack--200.njk
  components/vf-stack/vf-stack--500.njk
  components/vf-stack/vf-stack.config.yml
  components/vf-stack/vf-stack.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#1424 fixes issue with squishy inputs
  components/vf-form__checkbox/vf-form__checkbox.scss
  components/vf-form__radio/vf-form__radio.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#1425 Bug: vf-card item alignment
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/vf-card-container.config.yml
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
  tools/vf-component-library/src/site/index.njk
Labels: Type: Bug

#1427 adds word-break: break-word
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
Labels: Priority: Medium, Type: Bug, Type: Component or Pattern

#1421 the one that tentatively introduces a new (old) layout component.
  components/vf-componenet-rollup/index.scss
  components/vf-flag/.npmignore
  components/vf-flag/CHANGELOG.md
  components/vf-flag/README.md
  components/vf-flag/index.scss
  components/vf-flag/package.json
  components/vf-flag/vf-flag.config.yml
  components/vf-flag/vf-flag.js
  components/vf-flag/vf-flag.njk
  components/vf-flag/vf-flag.react.js
  components/vf-flag/vf-flag.scss
  components/vf-flag/vf-flag.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Documentation

#1434 Bug: vf-form fix name from "@visual-framework/form "
  components/vf-form/package.json
Labels: Priority: Critical, Type: Bug

#1435 Chore: update highlightjs syntax
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/package.json
  tools/vf-extensions/CHANGELOG.md
  tools/vf-extensions/tags/codeblock.js
  tools/vf-extensions/tags/render.js
  tools/vf-frctl-extensions/CHANGELOG.md
  tools/vf-frctl-extensions/codeblock.js
Labels: Priority: Medium, Type: Chore

#1436 The One That Adds Neutral Colour Tokens
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/json/vf-color__neutral.ios.json
  components/vf-design-tokens/dist/json/vf-colors.ios.json
  components/vf-design-tokens/dist/json/vf-ui-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-color__neutral.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-color__neutral.map.scss
  components/vf-design-tokens/gulpfile.js
  components/vf-design-tokens/src/maps/vf-color__neutral.yml
  components/vf-design-tokens/src/maps/vf-colors.yml
  components/vf-design-tokens/src/maps/vf-ui-colors.yml
  components/vf-design-tokens/src/neutral.palette.alias.yml
  components/vf-design-tokens/src/spacing.palette.alias.yml
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/functions/_set-color.scss
  components/vf-sass-config/variables/vf-variables.scss
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/package-lock.json
  tools/vf-component-library/package.json
  tools/vf-component-library/src/site/_data/tokens/breakpoints.js
  tools/vf-component-library/src/site/_data/tokens/colours.js
  tools/vf-component-library/src/site/_data/tokens/neutral_colours.js
  tools/vf-component-library/src/site/_data/tokens/spacing.js
  tools/vf-component-library/src/site/_data/tokens/theming.js
  tools/vf-component-library/src/site/_data/tokens/typographyMono.js
  tools/vf-component-library/src/site/_data/tokens/typographySans.js
  tools/vf-component-library/src/site/_data/tokens/uiColors.js
  tools/vf-component-library/src/site/design-tokens/colours.njk
  tools/vf-component-library/src/site/design-tokens/neutral-colors.njk
Labels: Priority: Medium, Status: Review Needed, Type: Breaking Change, Type: Enhancement

#1437 Adds more documentation to the Design Tokens documentation home page.
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/design-tokens/index.njk
Labels: Priority: Low, Status: Review Needed, Type: Documentation, Type: Enhancement

#1438 The one that makes the hero component a baller, a little less taller.
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#1439 The one that corrects the naming of neutral colour design tokens
  components/vf-design-tokens/dist/json/vf-color__neutral.ios.json
  components/vf-design-tokens/dist/json/vf-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-color__neutral.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-color__neutral.map.scss
  components/vf-design-tokens/src/maps/vf-color__neutral.yml
  components/vf-design-tokens/src/maps/vf-colors.yml
  components/vf-design-tokens/src/neutral.palette.alias.yml
Labels: Priority: Low, Status: Review Needed, Type: Bug

#1442 the one that fixes the embl grey and neutral 300 to match
  components/vf-design-tokens/dist/json/vf-color__neutral.ios.json
  components/vf-design-tokens/dist/json/vf-colors.ios.json
  components/vf-design-tokens/dist/sass/custom-properties/vf-color__neutral.custom-properties.scss
  components/vf-design-tokens/dist/sass/maps/vf-color__neutral.map.scss
  components/vf-design-tokens/src/maps/vf-colors.yml
  components/vf-design-tokens/src/neutral.palette.alias.yml
Labels: Priority: High, Status: Review Needed, Type: Bug

#1441 the one that fixes a few things in forms
  components/vf-form__fieldset/vf-form__fieldset.config.yml
  components/vf-form__fieldset/vf-form__fieldset.njk
  components/vf-form__fieldset/vf-form__fieldset.scss
  components/vf-form__legend/vf-form__legend.config.yml
  components/vf-form__legend/vf-form__legend.njk
  components/vf-form__legend/vf-form__legend.scss
  components/vf-form__radio/vf-form__radio.config.yml
  components/vf-form__radio/vf-form__radio.scss
Labels: Priority: Medium, Status: Review Needed, Type: Component or Pattern, Type: Refactor

#1440 The one that introduces a flexible, intrinsic sidebar layout component
  components/vf-componenet-rollup/index.scss
  components/vf-sidebar/.npmignore
  components/vf-sidebar/CHANGELOG.md
  components/vf-sidebar/README.md
  components/vf-sidebar/index.scss
  components/vf-sidebar/package.json
  components/vf-sidebar/vf-sidebar.config.yml
  components/vf-sidebar/vf-sidebar.js
  components/vf-sidebar/vf-sidebar.njk
  components/vf-sidebar/vf-sidebar.scss
  components/vf-sidebar/vf-sidebar.variables.scss
Labels: Priority: High, Status: Review Needed, Type: Component or Pattern, Type: Feature

#1445 the one that adds status updates to component pages in the 11ty docs site
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/src/site/_includes/layouts/components.njk
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#1446 the one that adds CSS class implementation guidance
  components/vf-stack/CHANGELOG.md
  components/vf-stack/README.md
Labels: Priority: High, Status: Review Needed, Type: Documentation, Type: Enhancement

#1447 the one that removes the weird examples
  components/vf-sidebar/CHANGELOG.md
  components/vf-sidebar/vf-sidebar.config.yml
  components/vf-sidebar/vf-sidebar.njk
Labels: Priority: High, Status: Review Needed, Type: Documentation

#1449 The one that fixes issues with browsers and forms being required
  components/vf-form__input/CHANGELOG.md
  components/vf-form__input/README.md
  components/vf-form__input/vf-form__input.config.yml
  components/vf-form__input/vf-form__input.njk
  components/vf-form__input/vf-form__input.scss
Labels: Priority: Medium, Status: Review Needed, Type: Breaking Change, Type: Bug

#1450 Chore: dp and analytics
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/scripts.njk
Labels: Type: Chore

#1451 the one that fixes a little max-width space issue on the `vf-body`
  components/vf-body/CHANGELOG.md
  components/vf-body/README.md
  components/vf-body/vf-body.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug

#1454 Bug: vf-form version and vf-masthead js function
  components/vf-componenet-rollup/CHANGELOG.md
  components/vf-componenet-rollup/index.scss
  components/vf-componenet-rollup/scripts.js
  components/vf-content/CHANGELOG.md
  components/vf-content/package.json
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead.js
Labels: Priority: Critical, Type: Bug

#1455 The one that reworks vf-search, again
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-variables.scss
  components/vf-search/CHANGELOG.md
  components/vf-search/README.md
  components/vf-search/vf-search.config.yml
  components/vf-search/vf-search.njk
  components/vf-search/vf-search.scss
Labels: Priority: Medium, Status: Review Needed, Type: Breaking Change, Type: Component or Pattern, Type: Documentation, Type: Refactor

#1459 documentation: component status
  tools/vf-component-library/src/site/_includes/layouts/components.njk
Labels: Type: Documentation

#1460 Bug: vf-sass-config neutral lookup function
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/functions/_set-color.scss
Labels: Priority: Critical, Type: Bug

#1461 status updates pre-release
  components/ebi-header-footer/ebi-header-footer.config.yml
  components/ebi-vf1-integration/ebi-vf1-integration.config.yml
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.config.yml
  components/embl-conditional-edit/embl-conditional-edit.config.yml
  components/embl-notifications/embl-notifications.config.yml
  components/vf-analytics-google/vf-analytics-google.config.yml
  components/vf-card/vf-card.config.yml
  components/vf-cluster/vf-cluster.config.yml
  components/vf-collapse/vf-collapse.config.yml
  components/vf-form/vf-form.config.yml
  components/vf-form__checkbox/vf-form__checkbox.config.yml
  components/vf-form__fieldset/vf-form__fieldset.config.yml
  components/vf-form__helper/vf-form__helper.config.yml
  components/vf-form__input/vf-form__input.config.yml
  components/vf-form__item/vf-form__item.config.yml
  components/vf-form__label/vf-form__label.config.yml
  components/vf-form__legend/vf-form__legend.config.yml
  components/vf-form__radio/vf-form__radio.config.yml
  components/vf-form__select/vf-form__select.config.yml
  components/vf-form__textarea/vf-form__textarea.config.yml
  components/vf-hero/vf-hero.config.yml
  components/vf-polyfill-js/vf-polyfill-js.config.yml
  components/vf-sass-starter/vf-sass-starter.config.yml
  components/vf-search-client-side/vf-search-client-side.config.yml
  components/vf-search/vf-search.config.yml
  components/vf-show-more/vf-show-more.config.yml
  components/vf-sidebar/vf-sidebar.config.yml
  components/vf-stack/vf-stack.config.yml
  components/vf-u-fullbleed/vf-u-fullbleed.config.yml
Labels: Priority: Low, Status: Review Needed

#1465 the one that deprecates the phase variant of the banner
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner--inline.njk
  components/vf-banner/vf-banner--phase.scss
  components/vf-banner/vf-banner.config.yml
Labels: Priority: Low, Status: Review Needed, Type: Changelog, Type: Refactor

#1468 Refactore: template markdown
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/design-kit/index.njk
  tools/vf-component-library/src/site/design-tokens/index.njk
  tools/vf-component-library/src/site/developing/components/deprecating-components.njk
  tools/vf-component-library/src/site/developing/getting-started/code-of-conduct.njk
  tools/vf-component-library/src/site/developing/getting-started/pull-requests.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/developing/getting-started/structure.njk
  tools/vf-component-library/src/site/developing/guidelines/governance.njk
  tools/vf-component-library/src/site/guidance/browser-support.md
  tools/vf-component-library/src/site/guidance/content-guidelines.md
  tools/vf-component-library/src/site/guidance/css-and-sass.md
  tools/vf-component-library/src/site/guidance/discussing-the-vf.njk
  tools/vf-component-library/src/site/guidance/image-handling.md
  tools/vf-component-library/src/site/guidance/index.njk
  tools/vf-component-library/src/site/guidance/javascript.md
  tools/vf-component-library/src/site/guidance/language-british-american-english.md
  tools/vf-component-library/src/site/guidance/user-base.md
  tools/vf-component-library/src/site/patterns/index.njk
Labels: Type: Enhancement
