Repository visual-framework/vf-core, pull requests merged in 2021-02, with the labels that each got.

#1336 bug: ebi-vf1-buttons
  components/ebi-vf1-integration/CHANGELOG.md
  components/ebi-vf1-integration/ebi-vf1-integration.scss
Labels: Type: Bug

#1337 Improves docs in a few places
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/about/index.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/design-tokens/index.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/developing/index.njk
  tools/vf-component-library/src/site/guidance/index.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/index.njk
Labels: Type: Documentation

#1341 The one that moves things around in the component library views
  tools/vf-component-library/src/site/_includes/layouts/components.njk
Labels: Priority: Low, Status: Feedback Needed, Status: Review Needed, Type: Documentation, Type: Refactor

#1342 Fix builds: changelog inclusions fails on CI
  components/vf-intro/CHANGELOG.md
  tools/vf-component-library/src/site/_includes/layouts/components.njk
  tools/vf-component-library/yarn.lock
Labels: Priority: Critical, Type: Bug

#1344 adds design principles to documentation site
  tools/vf-component-library/src/site/_includes/navigation.njk
  tools/vf-component-library/src/site/design-principles/index.njk
Labels: Status: Review Needed, Type: Documentation

#1343 Starts adding 'design token decisions'
  components/vf-design-tokens/dist/sass/maps/vf-color__background.map.scss
  components/vf-design-tokens/dist/sass/maps/vf-color__brand.map.scss
  components/vf-design-tokens/dist/sass/maps/vf-color__buttons.map.scss
  components/vf-design-tokens/dist/sass/maps/vf-color__text.map.scss
  components/vf-design-tokens/gulpfile.js
  components/vf-design-tokens/src/maps/vf-color__background.yml
  components/vf-design-tokens/src/maps/vf-color__brand.yml
  components/vf-design-tokens/src/maps/vf-color__buttons.yml
  components/vf-design-tokens/src/maps/vf-color__text.yml
  components/vf-design-tokens/src/theme.palette.alias.yml
Labels: Priority: Low, Status: Feedback Needed, Status: Review Needed, Type: Enhancement

#1349 The greatest documentation quest 2020 - vf-breadcrumb edition.
  components/vf-breadcrumbs/CHANGELOG.md
  components/vf-breadcrumbs/README.md
Labels: Priority: Low, Status: Review Needed, Type: Component or Pattern, Type: Documentation

#1352 Docs: Write browser support approach
  tools/vf-component-library/src/site/_includes/component-docs.njk
  tools/vf-component-library/src/site/guidance/browser-support.md
Labels: Type: Documentation

#1348 The greatest documentation quest 2020 - vf-button edition.
  components/vf-button/CHANGELOG.md
  components/vf-button/README.md
  components/vf-button/vf-button.config.yml
Labels: Priority: Low, Status: Review Needed, Type: Component or Pattern, Type: Documentation

#1355 updates vf-section-header svg
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.njk
  components/vf-section-header/vf-section-header.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug, Type: Refactor

#1354 brings the cards on the homepage inline with the newest designs
  tools/vf-component-library/CHANGELOG.md
  tools/vf-component-library/src/site/index.njk
Labels: Priority: Low, Status: Review Needed, Type: Documentation

#1366 fixes a margin issue
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug, Type: Refactor

#1376 updates blockquote to remove pullquote
  components/vf-blockquote/CHANGELOG.md
  components/vf-blockquote/vf-blockquote--pullquote.njk
  components/vf-blockquote/vf-blockquote.config.yml
  components/vf-blockquote/vf-blockquote.njk
  components/vf-blockquote/vf-blockquote.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#1375 BUG: vf-card issue with image height in Safari
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.config.yml
  components/vf-card/vf-card.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1357 Document use of Nunjucks include vs render
  tools/vf-component-library/src/site/_includes/layouts/components.njk
Labels: Type: Documentation

#1364 Docs: Create example error page boilerplates
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.config.yml
  components/vf-intro/vf-intro.njk
  tools/vf-component-library/src/site/patterns/error-pages.njk
Labels: Type: Documentation

#1367 removes all variants
  components/vf-hero/CHANGELOG.md
  components/vf-hero/README.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.njk
  components/vf-hero/vf-hero.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1386 updates vf-hero to demonstrate and style the heading link
  components/vf-hero/CHANGELOG.md
  components/vf-hero/README.md
  components/vf-hero/vf-hero.config.yml
  components/vf-hero/vf-hero.scss
Labels: Status: Review Needed, Type: Enhancement

#1379 Bug/vf card grid
  components/vf-card/CHANGELOG.md
  components/vf-card/README.md
  components/vf-card/vf-card.njk
  components/vf-card/vf-card.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug, Type: Refactor

#1380 updates card container to allow for aspect ratio
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/README.md
  components/vf-card-container/vf-card-container.config.yml
  components/vf-card-container/vf-card-container.njk
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#1385 the one that tidies up the general `vf-link` styles.
  components/vf-componenet-rollup/index.scss
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.scss
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/sass/vf-links.variables.scss
  components/vf-design-tokens/src/variables/vf-links.yml
  components/vf-link/CHANGELOG.md
  components/vf-link/index.scss
  components/vf-link/vf-link--disabled.scss
  components/vf-link/vf-link--example.njk
  components/vf-link/vf-link--primary.scss
  components/vf-link/vf-link--secondary.scss
  components/vf-link/vf-link.njk
  components/vf-link/vf-link.scss
  components/vf-link/vf-link.variables.scss
  components/vf-summary/CHANGELOG.md
  components/vf-summary/index.scss
  components/vf-summary/vf-summary.variables.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Refactor

#1392 the ones that resolves fractal wanting to render when using render in readmes
  components/vf-card/CHANGELOG.md
  components/vf-card/README.md
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1391 the one that fixes a non-existant link-color--disabled
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/mixins/vf-disabled.scss
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1389 Docs: content guide
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/design-kit/index.njk
  tools/vf-component-library/src/site/guidance/content-guidelines.md
  tools/vf-component-library/src/site/index.njk
Labels: Type: Documentation

#1378 fix: vf-logo extreme
  components/vf-logo/CHANGELOG.md
  components/vf-logo/vf-logo.config.yml
  components/vf-logo/vf-logo.scss
Labels: Type: Bug

#1393 the one that where we fix fractal wanting to render when using render in readmes
  components/vf-card-container/CHANGELOG.md
  components/vf-card-container/README.md
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#1396 the one that fixes alignment issues when card text is across several lines
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
Labels: Priority: Low, Status: Review Needed, Type: Bug
