Repository visual-framework/vf-core, pull requests merged in 2021-04, with the labels that each got.

#1467 some updates to the component library pages
  tools/vf-component-library/src/site/_includes/component-docs.njk
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/design-kit/index.njk
  tools/vf-component-library/src/site/design-tokens/index.njk
  tools/vf-component-library/src/site/developing/components/deprecating-components.njk
  tools/vf-component-library/src/site/developing/getting-started/code-of-conduct.njk
  tools/vf-component-library/src/site/developing/getting-started/pull-requests.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/developing/getting-started/structure.njk
  tools/vf-component-library/src/site/developing/guidelines/governance.njk
  tools/vf-component-library/src/site/guidance/browser-support.md
  tools/vf-component-library/src/site/guidance/content-guidelines.md
  tools/vf-component-library/src/site/guidance/css-and-sass.md
  tools/vf-component-library/src/site/guidance/discussing-the-vf.njk
  tools/vf-component-library/src/site/guidance/image-handling.md
  tools/vf-component-library/src/site/guidance/index.njk
  tools/vf-component-library/src/site/guidance/javascript.md
  tools/vf-component-library/src/site/guidance/language-british-american-english.md
  tools/vf-component-library/src/site/guidance/user-base.md
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/index.njk
Labels: Priority: Medium, Status: WIP, Type: Documentation, Type: Refactor

#1475 bug: vf-sass-config utility mixins import
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/index.scss
Labels: Priority: High, Type: Bug

#1478 Fix/broken import variable
  components/vf-masthead/CHANGELOG.md
  components/vf-masthead/vf-masthead.js
  components/vf-navigation/CHANGELOG.md
  components/vf-navigation/index.scss
  components/vf-navigation/package.json
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/mixins/_links.scss
  package.json
  tools/vf-component-library/src/site/_includes/component-docs.njk
  yarn.lock
Labels: Priority: Medium, Type: Bug

#1479 docs: accessibility
  tools/vf-component-generator/CHANGELOG.md
  tools/vf-component-generator/templates/_README.md
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/guidance/accessibility.md
Labels: Type: Documentation

#1485 enhancement: vf-hero safe text
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.njk
Labels: Type: Enhancement

#1486 the one that updates and deprecates bits of the table
  components/vf-table/CHANGELOG.md
  components/vf-table/vf-table.config.yml
  components/vf-table/vf-table.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1487 the one. that corrects link colour when hovering on visited link
  components/vf-card/CHANGELOG.md
  components/vf-card/vf-card.scss
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#1484 Docs: rough edges
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/developing/index.njk
Labels: Type: Documentation

#1489 enhancement: component structure
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/navigation.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic-embl-ebi.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic.njk
  tools/vf-component-library/src/site/patterns/error-pages.njk
  tools/vf-component-library/src/site/patterns/index.njk
  tools/vf-component-library/src/site/patterns/navigation.md
  tools/vf-component-library/src/site/patterns/scientific-service.njk
  tools/vf-component-library/src/site/patterns/search-results.njk
  tools/vf-component-library/src/site/patterns/sidebar.njk
Labels: Type: Documentation, Type: Enhancement

#1499 the one that changes how width works so it responds to viewport
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.scss
Labels: Priority: High, Status: Review Needed, Type: Bug, Type: Component or Pattern

#1508 Docs: usage guidance position
  tools/vf-component-library/src/site/_includes/layouts/components.njk
Labels: Type: Documentation

#1510 Patterns: refresh example boilerplates
  components/ebi-header-footer/CHANGELOG.md
  components/ebi-header-footer/ebi-header-footer--header.njk
  components/vf-content/CHANGELOG.md
  components/vf-content/vf-content.njk
  components/vf-content/vf-content.scss
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/vf-tabs.njk
  tools/vf-component-library/src/site/_includes/scripts.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/patterns/article.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic-embl-ebi.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic.njk
  tools/vf-component-library/src/site/patterns/error-pages.njk
  tools/vf-component-library/src/site/patterns/scientific-service.njk
  tools/vf-component-library/src/site/patterns/search-results.njk
  tools/vf-component-library/src/site/patterns/templates/breadcrumbs-boilerplate.njk
  tools/vf-component-library/src/site/patterns/templates/source-link-boilerplate.njk
  tools/vf-component-library/yarn.lock
Labels: Type: Documentation
