Repository visual-framework/vf-core, pull requests merged in 2021-05, with the labels that each got.

#1512 docs: update-roadmap
  tools/vf-component-library/src/site/about/roadmap.njk
Labels: Type: Documentation

#1515 Docs: component library navigation
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/layouts/base.njk
  tools/vf-component-library/src/site/_includes/navigation.njk
  tools/vf-component-library/src/site/about/index.njk
  tools/vf-component-library/src/site/design-principles/index.njk
  tools/vf-component-library/src/site/index.njk
  tools/vf-component-library/src/site/patterns/index.njk
Labels: Type: Documentation

#1527 the one that makes it possible to use HTML in a section header text item
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.config.yml
  components/vf-section-header/vf-section-header.njk
  components/vf-section-header/vf-section-header.scss
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#1526 Pattern, docs: add a no-js error page example
  tools/vf-component-library/src/site/_data/siteConfig.js
  tools/vf-component-library/src/site/_includes/layouts/section.njk
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/guidance/index.njk
  tools/vf-component-library/src/site/guidance/javascript-required.md
  tools/vf-component-library/src/site/guidance/javascript.md
  tools/vf-component-library/src/site/patterns/error-pages.njk
Labels: Type: Component or Pattern, Type: Documentation

#1533 bug: vf-analytics-google ahs undefined variable
  components/vf-analytics-google/CHANGELOG.md
  components/vf-analytics-google/vf-analytics-google.js
Labels: Priority: Medium, Type: Bug

#1528 Component: embl-breadcrumbs-lookup enhancements
  components/embl-breadcrumbs-lookup/CHANGELOG.md
  components/embl-breadcrumbs-lookup/README.md
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.config.yml
  components/embl-breadcrumbs-lookup/embl-breadcrumbs-lookup.js
Labels: Type: Component or Pattern

#1544 the one that updates sortable button icon and paves way for JS interactivty
  components/vf-table/CHANGELOG.md
  components/vf-table/vf-table.config.yml
  components/vf-table/vf-table.njk
  components/vf-table/vf-table.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1534 the one that chips away at the `vf-tree` component
  components/vf-tree/CHANGELOG.md
  components/vf-tree/vf-tree.config.yml
  components/vf-tree/vf-tree.js
  components/vf-tree/vf-tree.njk
  components/vf-tree/vf-tree.scss
Labels: Priority: Medium, Status: WIP, Type: Breaking Change, Type: Enhancement, Type: Refactor

#1543 the one that adds context to summaries
  components/vf-summary/CHANGELOG.md
  components/vf-summary/vf-summary--article.njk
  components/vf-summary/vf-summary--event.njk
  components/vf-summary/vf-summary--has-image.njk
  components/vf-summary/vf-summary--job.njk
  components/vf-summary/vf-summary--news-has-image.njk
  components/vf-summary/vf-summary--news.njk
  components/vf-summary/vf-summary--publication.njk
  components/vf-summary/vf-summary.config.yml
  components/vf-summary/vf-summary.njk
Labels: Status: Review Needed

#1549 the one that reduces the variants of pagination
  components/vf-pagination/CHANGELOG.md
  components/vf-pagination/vf-pagination--full.scss
  components/vf-pagination/vf-pagination.config.yml
  components/vf-pagination/vf-pagination.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1551 the one that updates tabs to match to current design direction
  components/vf-tabs/CHANGELOG.md
  components/vf-tabs/vf-tabs.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Refactor

#1553 The one that enhances the `vf-summary` `alt` text if the image is purely decorative.
  components/vf-summary/README.md
  components/vf-summary/vf-summary--has-decorative-image.njk
  components/vf-summary/vf-summary.config.yml
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#1548 the one that makes buttons stick to their naming convention rather than 'fake it'
  components/vf-button/CHANGELOG.md
  components/vf-button/vf-button.config.yml
  components/vf-button/vf-button.scss
Labels: Priority: Medium, Status: Review Needed, Type: Refactor

#1554 the one that makes the tree arrows the right way around
  components/vf-tree/vf-tree.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1552 the one that updates blockquote to allow for use with context and a bit more
  components/vf-blockquote/CHANGELOG.md
  components/vf-blockquote/vf-blockquote.config.yml
  components/vf-blockquote/vf-blockquote.njk
  components/vf-blockquote/vf-blockquote.scss
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Refactor

#1547 the one that makes `vf-stack` dictate the flow of things a bit better
  components/embl-content-hub-loader/CHANGELOG.md
  components/embl-content-hub-loader/embl-content-hub-loader.scss
  components/vf-banner/CHANGELOG.md
  components/vf-banner/vf-banner.scss
  components/vf-global-header/vf-global-header.scss
Labels: Priority: Medium, Status: Review Needed, Type: Strategic

#1546 the one that updates to badges to make them consistent with buttons
  components/vf-badge/CHANGELOG.md
  components/vf-badge/vf-badge.config.yml
  components/vf-badge/vf-badge.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1555 the final one that updates all relevant Sass linting errors
  components/vf-back-to-top/vf-back-to-top.scss
  components/vf-button/vf-button.scss
  components/vf-componenet-rollup/scripts.js
  components/vf-form__legend/vf-form__legend.scss
  components/vf-navigation/vf-navigation.scss
  components/vf-search/vf-search.scss
  components/vf-section-header/vf-section-header.scss
  components/vf-sidebar/vf-sidebar.scss
  components/vf-table/vf-table.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor
