Repository visual-framework/vf-core, pull requests merged in 2021-01, with the labels that each got.

#1311 Chore: cleanup vf dependencies
  components/vf-show-more/vf-show-more.js
  components/vf-tabs/vf-tabs.js
  tools/vf-component-library/package.json
  tools/vf-core/gulp-tasks/vf-assets.js
  tools/vf-core/gulp-tasks/vf-build.js
  tools/vf-core/gulp-tasks/vf-cleanup.js
  tools/vf-core/gulp-tasks/vf-component.js
  tools/vf-core/gulp-tasks/vf-css.js
  tools/vf-core/gulp-tasks/vf-fractal.js
  tools/vf-core/gulp-tasks/vf-scripts.js
  tools/vf-core/gulp-tasks/vf-templates-precompile.js
  tools/vf-core/gulp-tasks/vf-watch.js
  tools/vf-core/package.json
  tools/vf-sass-compilation/CHANGELOG.md
  tools/vf-sass-compilation/package.json
Labels: Type: Chore

#1316 Chore: update ebi footer template
  components/ebi-header-footer/CHANGELOG.md
  components/ebi-header-footer/README.md
  components/ebi-header-footer/ebi-header-footer--footer.njk
  components/ebi-header-footer/ebi-header-footer--header.njk
  components/ebi-header-footer/ebi-header-footer.config.yml
  components/ebi-header-footer/ebi-header-footer.njk
Labels: Type: Chore

#1326 Bug: vf-intro usage of vf_intro_subheading
  components/vf-intro/CHANGELOG.md
  components/vf-intro/README.md
  components/vf-intro/vf-intro.njk
Labels: Type: Bug

#1325 Pattersn: embl and ebi boilerplate
  .vscode/settings.json
  components/ebi-header-footer/CHANGELOG.md
  components/ebi-header-footer/ebi-header-footer--header.scss
  tools/vf-component-library/src/site/_data/containers.json
  tools/vf-component-library/src/site/_includes/footer.njk
  tools/vf-component-library/src/site/_includes/scripts.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic-embl-ebi.njk
  tools/vf-component-library/src/site/patterns/boilerplate-generic.njk
  tools/vf-component-library/src/site/patterns/sidebar.njk
Labels: Type: Documentation

#1317 bug: section-header-closing-tag
  components/vf-section-header/CHANGELOG.md
  components/vf-section-header/vf-section-header.njk
Labels: Priority: Medium, Type: Bug

#1324 Docs: setting up
  tools/vf-component-library/src/site/building/index.njk
  tools/vf-component-library/src/site/developing/getting-started/setting-up.njk
  tools/vf-component-library/src/site/index.njk
Labels: Type: Documentation

#1327 Docs: component infromation
  tools/vf-component-library/src/site/_includes/component-docs.njk
  tools/vf-component-library/src/site/components/index.njk
  tools/vf-component-library/src/site/guidance/components-and-patterns.md
  tools/vf-component-library/src/site/guidance/creating-components.md
  tools/vf-component-library/src/site/guidance/versioning-and-component-interoperability.md
Labels: Type: Documentation

#1274 fix(vf-intro): move the example content
  components/vf-intro/CHANGELOG.md
  components/vf-intro/vf-intro.config.yml
Labels: Priority: Low, Status: Review Needed, Type: Bug

#1285 the one that improves spacing and usability of video teaser
  components/vf-video-teaser/CHANGELOG.md
  components/vf-video-teaser/vf-video-teaser.config.yml
  components/vf-video-teaser/vf-video-teaser.njk
  components/vf-video-teaser/vf-video-teaser.scss
Labels: Priority: Medium, Status: Review Needed, Type: Breaking Change, Type: Refactor

#1328 fixes some issues with vf-grid when in IE11 land
  components/vf-grid/CHANGELOG.md
  components/vf-grid/vf-grid.scss
Labels: Priority: High, Status: Review Needed, Type: Bug

#1331 Chore: use feature to disable banner from EBI VF 1.4
  components/ebi-header-footer/CHANGELOG.md
  components/ebi-header-footer/README.md
  components/ebi-header-footer/ebi-header-footer--header.njk
Labels: Type: Chore, Type: Enhancement

#1333 small changes to the max-width
  components/vf-body/CHANGELOG.md
  components/vf-body/README.md
  components/vf-body/vf-body.scss
  components/vf-design-tokens/CHANGELOG.md
  components/vf-design-tokens/dist/sass/vf-layout.variables.scss
  components/vf-design-tokens/src/variables/vf-layout.yml
  components/vf-sass-config/CHANGELOG.md
  components/vf-sass-config/variables/vf-global-variables.scss
Labels: Priority: Low, Status: Review Needed, Type: Refactor

#1335 fixes missing herf from context
  components/vf-hero/CHANGELOG.md
  components/vf-hero/vf-hero.njk
Labels: Priority: Critical, Status: Review Needed, Type: Bug
